// A curated few hundred Twemoji (CC-BY 4.0, see assets/emoji/LICENSE-GRAPHICS.txt)
// the player can place as marks. An emoji becomes an ordinary SVG mark when
// it is placed, drawn in its own colours or tinted like any other.

export interface Emoji {
  code: string;
  char: string;
  name: string;
  group: string;
  /** The raw SVG. */
  svg: string;
}

export const EMOJI_GROUPS: [string, string][] = [
  ["smileys", "Smileys"],
  ["people", "Body"],
  ["nature", "Nature"],
  ["food", "Food"],
  ["travel", "Travel"],
  ["activities", "Activities"],
  ["objects", "Objects"],
  ["symbols", "Symbols"],
  ["flags", "Flags"],
];

const FILES = import.meta.glob<string>("../assets/emoji/*.svg", { query: "?raw", import: "default", eager: true });

/** Code, character, name and group. */
const LIST: [string, string, string, string][] = [
  ["1f600", "😀", "Grinning face", "smileys"],
  ["1f603", "😃", "Grinning face with big eyes", "smileys"],
  ["1f604", "😄", "Grinning face with smiling eyes", "smileys"],
  ["1f601", "😁", "Beaming face with smiling eyes", "smileys"],
  ["1f606", "😆", "Grinning squinting face", "smileys"],
  ["1f605", "😅", "Grinning face with sweat", "smileys"],
  ["1f923", "🤣", "Rolling on the floor laughing", "smileys"],
  ["1f602", "😂", "Face with tears of joy", "smileys"],
  ["1f642", "🙂", "Slightly smiling face", "smileys"],
  ["1f643", "🙃", "Upside-down face", "smileys"],
  ["1fae0", "🫠", "Melting face", "smileys"],
  ["1f609", "😉", "Winking face", "smileys"],
  ["1f60a", "😊", "Smiling face with smiling eyes", "smileys"],
  ["1f607", "😇", "Smiling face with halo", "smileys"],
  ["1f970", "🥰", "Smiling face with hearts", "smileys"],
  ["1f60d", "😍", "Smiling face with heart-eyes", "smileys"],
  ["1f929", "🤩", "Star-struck", "smileys"],
  ["1f618", "😘", "Face blowing a kiss", "smileys"],
  ["1f617", "😗", "Kissing face", "smileys"],
  ["263a", "☺️", "Smiling face", "smileys"],
  ["1f61a", "😚", "Kissing face with closed eyes", "smileys"],
  ["1f619", "😙", "Kissing face with smiling eyes", "smileys"],
  ["1f972", "🥲", "Smiling face with tear", "smileys"],
  ["1f60b", "😋", "Face savoring food", "smileys"],
  ["1f61b", "😛", "Face with tongue", "smileys"],
  ["1f61c", "😜", "Winking face with tongue", "smileys"],
  ["1f92a", "🤪", "Zany face", "smileys"],
  ["1f61d", "😝", "Squinting face with tongue", "smileys"],
  ["1f911", "🤑", "Money-mouth face", "smileys"],
  ["1f917", "🤗", "Smiling face with open hands", "smileys"],
  ["1f92d", "🤭", "Face with hand over mouth", "smileys"],
  ["1fae2", "🫢", "Face with open eyes and hand over mouth", "smileys"],
  ["1fae3", "🫣", "Face with peeking eye", "smileys"],
  ["1f92b", "🤫", "Shushing face", "smileys"],
  ["1f914", "🤔", "Thinking face", "smileys"],
  ["1fae1", "🫡", "Saluting face", "smileys"],
  ["1f910", "🤐", "Zipper-mouth face", "smileys"],
  ["1f928", "🤨", "Face with raised eyebrow", "smileys"],
  ["1f610", "😐", "Neutral face", "smileys"],
  ["1f611", "😑", "Expressionless face", "smileys"],
  ["1f636", "😶", "Face without mouth", "smileys"],
  ["1fae5", "🫥", "Dotted line face", "smileys"],
  ["1f60f", "😏", "Smirking face", "smileys"],
  ["1f612", "😒", "Unamused face", "smileys"],
  ["1f644", "🙄", "Face with rolling eyes", "smileys"],
  ["1f62c", "😬", "Grimacing face", "smileys"],
  ["1f925", "🤥", "Lying face", "smileys"],
  ["1fae8", "🫨", "Shaking face", "smileys"],
  ["1f60c", "😌", "Relieved face", "smileys"],
  ["1f614", "😔", "Pensive face", "smileys"],
  ["1f62a", "😪", "Sleepy face", "smileys"],
  ["1f924", "🤤", "Drooling face", "smileys"],
  ["1f634", "😴", "Sleeping face", "smileys"],
  ["1f637", "😷", "Face with medical mask", "smileys"],
  ["1f912", "🤒", "Face with thermometer", "smileys"],
  ["1f915", "🤕", "Face with head-bandage", "smileys"],
  ["1f922", "🤢", "Nauseated face", "smileys"],
  ["1f92e", "🤮", "Face vomiting", "smileys"],
  ["1f927", "🤧", "Sneezing face", "smileys"],
  ["1f975", "🥵", "Hot face", "smileys"],
  ["1f976", "🥶", "Cold face", "smileys"],
  ["1f974", "🥴", "Woozy face", "smileys"],
  ["1f635", "😵", "Face with crossed-out eyes", "smileys"],
  ["1f92f", "🤯", "Exploding head", "smileys"],
  ["1f920", "🤠", "Cowboy hat face", "smileys"],
  ["1f973", "🥳", "Partying face", "smileys"],
  ["1f978", "🥸", "Disguised face", "smileys"],
  ["1f60e", "😎", "Smiling face with sunglasses", "smileys"],
  ["1f913", "🤓", "Nerd face", "smileys"],
  ["1f9d0", "🧐", "Face with monocle", "smileys"],
  ["1f615", "😕", "Confused face", "smileys"],
  ["1fae4", "🫤", "Face with diagonal mouth", "smileys"],
  ["1f61f", "😟", "Worried face", "smileys"],
  ["1f641", "🙁", "Slightly frowning face", "smileys"],
  ["2639", "☹️", "Frowning face", "smileys"],
  ["1f62e", "😮", "Face with open mouth", "smileys"],
  ["1f62f", "😯", "Hushed face", "smileys"],
  ["1f632", "😲", "Astonished face", "smileys"],
  ["1f633", "😳", "Flushed face", "smileys"],
  ["1f97a", "🥺", "Pleading face", "smileys"],
  ["1f979", "🥹", "Face holding back tears", "smileys"],
  ["1f626", "😦", "Frowning face with open mouth", "smileys"],
  ["1f627", "😧", "Anguished face", "smileys"],
  ["1f628", "😨", "Fearful face", "smileys"],
  ["1f624", "😤", "Face with steam from nose", "smileys"],
  ["1f621", "😡", "Enraged face", "smileys"],
  ["1f620", "😠", "Angry face", "smileys"],
  ["1f92c", "🤬", "Face with symbols on mouth", "smileys"],
  ["1f608", "😈", "Smiling face with horns", "smileys"],
  ["1f47f", "👿", "Angry face with horns", "smileys"],
  ["1f480", "💀", "Skull", "smileys"],
  ["2620", "☠️", "Skull and crossbones", "smileys"],
  ["1f4a9", "💩", "Pile of poo", "smileys"],
  ["1f921", "🤡", "Clown face", "smileys"],
  ["1f479", "👹", "Ogre", "smileys"],
  ["1f47a", "👺", "Goblin", "smileys"],
  ["1f47b", "👻", "Ghost", "smileys"],
  ["1f47d", "👽", "Alien", "smileys"],
  ["1f47e", "👾", "Alien monster", "smileys"],
  ["1f916", "🤖", "Robot", "smileys"],
  ["1f63a", "😺", "Grinning cat", "smileys"],
  ["1f638", "😸", "Grinning cat with smiling eyes", "smileys"],
  ["1f639", "😹", "Cat with tears of joy", "smileys"],
  ["1f63b", "😻", "Smiling cat with heart-eyes", "smileys"],
  ["1f63c", "😼", "Cat with wry smile", "smileys"],
  ["1f63d", "😽", "Kissing cat", "smileys"],
  ["1f640", "🙀", "Weary cat", "smileys"],
  ["1f63f", "😿", "Crying cat", "smileys"],
  ["1f63e", "😾", "Pouting cat", "smileys"],
  ["1f648", "🙈", "See-no-evil monkey", "smileys"],
  ["1f649", "🙉", "Hear-no-evil monkey", "smileys"],
  ["1f64a", "🙊", "Speak-no-evil monkey", "smileys"],
  ["1f48c", "💌", "Love letter", "smileys"],
  ["1f498", "💘", "Heart with arrow", "smileys"],
  ["1f49d", "💝", "Heart with ribbon", "smileys"],
  ["1f496", "💖", "Sparkling heart", "smileys"],
  ["1f497", "💗", "Growing heart", "smileys"],
  ["1f493", "💓", "Beating heart", "smileys"],
  ["1f49e", "💞", "Revolving hearts", "smileys"],
  ["1f495", "💕", "Two hearts", "smileys"],
  ["1f49f", "💟", "Heart decoration", "smileys"],
  ["2763", "❣️", "Heart exclamation", "smileys"],
  ["1f494", "💔", "Broken heart", "smileys"],
  ["2764", "❤️", "Red heart", "smileys"],
  ["1fa77", "🩷", "Pink heart", "smileys"],
  ["1f9e1", "🧡", "Orange heart", "smileys"],
  ["1f44b", "👋", "Waving hand", "people"],
  ["1f91a", "🤚", "Raised back of hand", "people"],
  ["1f590", "🖐️", "Hand with fingers splayed", "people"],
  ["270b", "✋", "Raised hand", "people"],
  ["1f596", "🖖", "Vulcan salute", "people"],
  ["1faf1", "🫱", "Rightwards hand", "people"],
  ["1faf2", "🫲", "Leftwards hand", "people"],
  ["1faf3", "🫳", "Palm down hand", "people"],
  ["1faf4", "🫴", "Palm up hand", "people"],
  ["1faf7", "🫷", "Leftwards pushing hand", "people"],
  ["1f44c", "👌", "OK hand", "people"],
  ["1f90c", "🤌", "Pinched fingers", "people"],
  ["1f90f", "🤏", "Pinching hand", "people"],
  ["270c", "✌️", "Victory hand", "people"],
  ["1f91e", "🤞", "Crossed fingers", "people"],
  ["1faf0", "🫰", "Hand with index finger and thumb crossed", "people"],
  ["1f91f", "🤟", "Love-you gesture", "people"],
  ["1f918", "🤘", "Sign of the horns", "people"],
  ["1f919", "🤙", "Call me hand", "people"],
  ["1f448", "👈", "Backhand index pointing left", "people"],
  ["1f449", "👉", "Backhand index pointing right", "people"],
  ["1f446", "👆", "Backhand index pointing up", "people"],
  ["1f595", "🖕", "Middle finger", "people"],
  ["1f447", "👇", "Backhand index pointing down", "people"],
  ["261d", "☝️", "Index pointing up", "people"],
  ["1faf5", "🫵", "Index pointing at the viewer", "people"],
  ["1f44d", "👍", "Thumbs up", "people"],
  ["1f44e", "👎", "Thumbs down", "people"],
  ["270a", "✊", "Raised fist", "people"],
  ["1f44a", "👊", "Oncoming fist", "people"],
  ["1f91b", "🤛", "Left-facing fist", "people"],
  ["1f91c", "🤜", "Right-facing fist", "people"],
  ["1f44f", "👏", "Clapping hands", "people"],
  ["1f64c", "🙌", "Raising hands", "people"],
  ["1faf6", "🫶", "Heart hands", "people"],
  ["1f450", "👐", "Open hands", "people"],
  ["1f932", "🤲", "Palms up together", "people"],
  ["1f91d", "🤝", "Handshake", "people"],
  ["1f64f", "🙏", "Folded hands", "people"],
  ["270d", "✍️", "Writing hand", "people"],
  ["1f485", "💅", "Nail polish", "people"],
  ["1f933", "🤳", "Selfie", "people"],
  ["1f4aa", "💪", "Flexed biceps", "people"],
  ["1f9be", "🦾", "Mechanical arm", "people"],
  ["1f9bf", "🦿", "Mechanical leg", "people"],
  ["1f9b5", "🦵", "Leg", "people"],
  ["1f9b6", "🦶", "Foot", "people"],
  ["1f442", "👂", "Ear", "people"],
  ["1f9bb", "🦻", "Ear with hearing aid", "people"],
  ["1f443", "👃", "Nose", "people"],
  ["1f9e0", "🧠", "Brain", "people"],
  ["1fac0", "🫀", "Anatomical heart", "people"],
  ["1f435", "🐵", "Monkey face", "nature"],
  ["1f412", "🐒", "Monkey", "nature"],
  ["1f98d", "🦍", "Gorilla", "nature"],
  ["1f9a7", "🦧", "Orangutan", "nature"],
  ["1f436", "🐶", "Dog face", "nature"],
  ["1f415", "🐕", "Dog", "nature"],
  ["1f9ae", "🦮", "Guide dog", "nature"],
  ["1f429", "🐩", "Poodle", "nature"],
  ["1f43a", "🐺", "Wolf", "nature"],
  ["1f98a", "🦊", "Fox", "nature"],
  ["1f99d", "🦝", "Raccoon", "nature"],
  ["1f431", "🐱", "Cat face", "nature"],
  ["1f983", "🦃", "Turkey", "nature"],
  ["1f414", "🐔", "Chicken", "nature"],
  ["1f413", "🐓", "Rooster", "nature"],
  ["1f423", "🐣", "Hatching chick", "nature"],
  ["1f424", "🐤", "Baby chick", "nature"],
  ["1f425", "🐥", "Front-facing baby chick", "nature"],
  ["1f426", "🐦", "Bird", "nature"],
  ["1f427", "🐧", "Penguin", "nature"],
  ["1f54a", "🕊️", "Dove", "nature"],
  ["1f985", "🦅", "Eagle", "nature"],
  ["1f986", "🦆", "Duck", "nature"],
  ["1f9a2", "🦢", "Swan", "nature"],
  ["1f438", "🐸", "Frog", "nature"],
  ["1f40a", "🐊", "Crocodile", "nature"],
  ["1f422", "🐢", "Turtle", "nature"],
  ["1f98e", "🦎", "Lizard", "nature"],
  ["1f40d", "🐍", "Snake", "nature"],
  ["1f432", "🐲", "Dragon face", "nature"],
  ["1f409", "🐉", "Dragon", "nature"],
  ["1f995", "🦕", "Sauropod", "nature"],
  ["1f996", "🦖", "T-Rex", "nature"],
  ["1f433", "🐳", "Spouting whale", "nature"],
  ["1f40b", "🐋", "Whale", "nature"],
  ["1f42c", "🐬", "Dolphin", "nature"],
  ["1f9ad", "🦭", "Seal", "nature"],
  ["1f41f", "🐟", "Fish", "nature"],
  ["1f420", "🐠", "Tropical fish", "nature"],
  ["1f421", "🐡", "Blowfish", "nature"],
  ["1f988", "🦈", "Shark", "nature"],
  ["1f419", "🐙", "Octopus", "nature"],
  ["1f41a", "🐚", "Spiral shell", "nature"],
  ["1fab8", "🪸", "Coral", "nature"],
  ["1fabc", "🪼", "Jellyfish", "nature"],
  ["1f40c", "🐌", "Snail", "nature"],
  ["1f98b", "🦋", "Butterfly", "nature"],
  ["1f41b", "🐛", "Bug", "nature"],
  ["1f41c", "🐜", "Ant", "nature"],
  ["1f41d", "🐝", "Honeybee", "nature"],
  ["1fab2", "🪲", "Beetle", "nature"],
  ["1f41e", "🐞", "Lady beetle", "nature"],
  ["1f997", "🦗", "Cricket", "nature"],
  ["1fab3", "🪳", "Cockroach", "nature"],
  ["1f577", "🕷️", "Spider", "nature"],
  ["1f578", "🕸️", "Spider web", "nature"],
  ["1f982", "🦂", "Scorpion", "nature"],
  ["1f490", "💐", "Bouquet", "nature"],
  ["1f338", "🌸", "Cherry blossom", "nature"],
  ["1f4ae", "💮", "White flower", "nature"],
  ["1fab7", "🪷", "Lotus", "nature"],
  ["1f3f5", "🏵️", "Rosette", "nature"],
  ["1f339", "🌹", "Rose", "nature"],
  ["1f940", "🥀", "Wilted flower", "nature"],
  ["1f33a", "🌺", "Hibiscus", "nature"],
  ["1f33b", "🌻", "Sunflower", "nature"],
  ["1f33c", "🌼", "Blossom", "nature"],
  ["1f337", "🌷", "Tulip", "nature"],
  ["1fabb", "🪻", "Hyacinth", "nature"],
  ["1f331", "🌱", "Seedling", "nature"],
  ["1fab4", "🪴", "Potted plant", "nature"],
  ["1f332", "🌲", "Evergreen tree", "nature"],
  ["1f333", "🌳", "Deciduous tree", "nature"],
  ["1f334", "🌴", "Palm tree", "nature"],
  ["1f335", "🌵", "Cactus", "nature"],
  ["1f33e", "🌾", "Sheaf of rice", "nature"],
  ["1f33f", "🌿", "Herb", "nature"],
  ["2618", "☘️", "Shamrock", "nature"],
  ["1f340", "🍀", "Four leaf clover", "nature"],
  ["1f341", "🍁", "Maple leaf", "nature"],
  ["1f342", "🍂", "Fallen leaf", "nature"],
  ["1f347", "🍇", "Grapes", "food"],
  ["1f348", "🍈", "Melon", "food"],
  ["1f349", "🍉", "Watermelon", "food"],
  ["1f34a", "🍊", "Tangerine", "food"],
  ["1f34b", "🍋", "Lemon", "food"],
  ["1f34c", "🍌", "Banana", "food"],
  ["1f34d", "🍍", "Pineapple", "food"],
  ["1f96d", "🥭", "Mango", "food"],
  ["1f34e", "🍎", "Red apple", "food"],
  ["1f34f", "🍏", "Green apple", "food"],
  ["1f951", "🥑", "Avocado", "food"],
  ["1f346", "🍆", "Eggplant", "food"],
  ["1f954", "🥔", "Potato", "food"],
  ["1f955", "🥕", "Carrot", "food"],
  ["1f33d", "🌽", "Ear of corn", "food"],
  ["1f336", "🌶️", "Hot pepper", "food"],
  ["1fad1", "🫑", "Bell pepper", "food"],
  ["1f952", "🥒", "Cucumber", "food"],
  ["1f96c", "🥬", "Leafy green", "food"],
  ["1f966", "🥦", "Broccoli", "food"],
  ["1f35e", "🍞", "Bread", "food"],
  ["1f950", "🥐", "Croissant", "food"],
  ["1f956", "🥖", "Baguette bread", "food"],
  ["1fad3", "🫓", "Flatbread", "food"],
  ["1f968", "🥨", "Pretzel", "food"],
  ["1f96f", "🥯", "Bagel", "food"],
  ["1f95e", "🥞", "Pancakes", "food"],
  ["1f9c7", "🧇", "Waffle", "food"],
  ["1f9c0", "🧀", "Cheese wedge", "food"],
  ["1f356", "🍖", "Meat on bone", "food"],
  ["1f371", "🍱", "Bento box", "food"],
  ["1f358", "🍘", "Rice cracker", "food"],
  ["1f359", "🍙", "Rice ball", "food"],
  ["1f35a", "🍚", "Cooked rice", "food"],
  ["1f35b", "🍛", "Curry rice", "food"],
  ["1f35c", "🍜", "Steaming bowl", "food"],
  ["1f35d", "🍝", "Spaghetti", "food"],
  ["1f360", "🍠", "Roasted sweet potato", "food"],
  ["1f362", "🍢", "Oden", "food"],
  ["1f363", "🍣", "Sushi", "food"],
  ["1f980", "🦀", "Crab", "food"],
  ["1f99e", "🦞", "Lobster", "food"],
  ["1f990", "🦐", "Shrimp", "food"],
  ["1f991", "🦑", "Squid", "food"],
  ["1f9aa", "🦪", "Oyster", "food"],
  ["1f366", "🍦", "Soft ice cream", "food"],
  ["1f367", "🍧", "Shaved ice", "food"],
  ["1f368", "🍨", "Ice cream", "food"],
  ["1f369", "🍩", "Doughnut", "food"],
  ["1f36a", "🍪", "Cookie", "food"],
  ["1f382", "🎂", "Birthday cake", "food"],
  ["1f370", "🍰", "Shortcake", "food"],
  ["1f9c1", "🧁", "Cupcake", "food"],
  ["1f967", "🥧", "Pie", "food"],
  ["1f36b", "🍫", "Chocolate bar", "food"],
  ["1f37c", "🍼", "Baby bottle", "food"],
  ["1f95b", "🥛", "Glass of milk", "food"],
  ["2615", "☕", "Hot beverage", "food"],
  ["1fad6", "🫖", "Teapot", "food"],
  ["1f375", "🍵", "Teacup without handle", "food"],
  ["1f376", "🍶", "Sake", "food"],
  ["1f37e", "🍾", "Bottle with popping cork", "food"],
  ["1f377", "🍷", "Wine glass", "food"],
  ["1f378", "🍸", "Cocktail glass", "food"],
  ["1f379", "🍹", "Tropical drink", "food"],
  ["1f962", "🥢", "Chopsticks", "food"],
  ["1f37d", "🍽️", "Fork and knife with plate", "food"],
  ["1f374", "🍴", "Fork and knife", "food"],
  ["1f944", "🥄", "Spoon", "food"],
  ["1f52a", "🔪", "Kitchen knife", "food"],
  ["1fad9", "🫙", "Jar", "food"],
  ["1f3fa", "🏺", "Amphora", "food"],
  ["1f30d", "🌍", "Globe showing Europe-Africa", "travel"],
  ["1f30e", "🌎", "Globe showing Americas", "travel"],
  ["1f30f", "🌏", "Globe showing Asia-Australia", "travel"],
  ["1f310", "🌐", "Globe with meridians", "travel"],
  ["1f5fa", "🗺️", "World map", "travel"],
  ["1f5fe", "🗾", "Map of Japan", "travel"],
  ["1f9ed", "🧭", "Compass", "travel"],
  ["1f3d4", "🏔️", "Snow-capped mountain", "travel"],
  ["26f0", "⛰️", "Mountain", "travel"],
  ["1f30b", "🌋", "Volcano", "travel"],
  ["1f5fb", "🗻", "Mount fuji", "travel"],
  ["1f3d5", "🏕️", "Camping", "travel"],
  ["1f3d6", "🏖️", "Beach with umbrella", "travel"],
  ["1f3dc", "🏜️", "Desert", "travel"],
  ["1f3dd", "🏝️", "Desert island", "travel"],
  ["1f3df", "🏟️", "Stadium", "travel"],
  ["1f3db", "🏛️", "Classical building", "travel"],
  ["1f3d7", "🏗️", "Building construction", "travel"],
  ["1f9f1", "🧱", "Brick", "travel"],
  ["1faa8", "🪨", "Rock", "travel"],
  ["1fab5", "🪵", "Wood", "travel"],
  ["1f6d6", "🛖", "Hut", "travel"],
  ["1f3d8", "🏘️", "Houses", "travel"],
  ["26f2", "⛲", "Fountain", "travel"],
  ["26fa", "⛺", "Tent", "travel"],
  ["1f301", "🌁", "Foggy", "travel"],
  ["1f303", "🌃", "Night with stars", "travel"],
  ["1f3d9", "🏙️", "Cityscape", "travel"],
  ["1f304", "🌄", "Sunrise over mountains", "travel"],
  ["1f305", "🌅", "Sunrise", "travel"],
  ["1f306", "🌆", "Cityscape at dusk", "travel"],
  ["1f682", "🚂", "Locomotive", "travel"],
  ["1f683", "🚃", "Railway car", "travel"],
  ["1f684", "🚄", "High-speed train", "travel"],
  ["1f685", "🚅", "Bullet train", "travel"],
  ["1f686", "🚆", "Train", "travel"],
  ["1f687", "🚇", "Metro", "travel"],
  ["1f688", "🚈", "Light rail", "travel"],
  ["1f689", "🚉", "Station", "travel"],
  ["2693", "⚓", "Anchor", "travel"],
  ["1f6df", "🛟", "Ring buoy", "travel"],
  ["26f5", "⛵", "Sailboat", "travel"],
  ["1f6f6", "🛶", "Canoe", "travel"],
  ["1f6a4", "🚤", "Speedboat", "travel"],
  ["1f6f3", "🛳️", "Passenger ship", "travel"],
  ["26f4", "⛴️", "Ferry", "travel"],
  ["1f6e5", "🛥️", "Motor boat", "travel"],
  ["2708", "✈️", "Airplane", "travel"],
  ["1f6e9", "🛩️", "Small airplane", "travel"],
  ["1f6eb", "🛫", "Airplane departure", "travel"],
  ["1f6ec", "🛬", "Airplane arrival", "travel"],
  ["1fa82", "🪂", "Parachute", "travel"],
  ["1f4ba", "💺", "Seat", "travel"],
  ["1f681", "🚁", "Helicopter", "travel"],
  ["1f69f", "🚟", "Suspension railway", "travel"],
  ["1f6ce", "🛎️", "Bellhop bell", "travel"],
  ["1f9f3", "🧳", "Luggage", "travel"],
  ["231b", "⌛", "Hourglass done", "travel"],
  ["23f3", "⏳", "Hourglass not done", "travel"],
  ["231a", "⌚", "Watch", "travel"],
  ["23f0", "⏰", "Alarm clock", "travel"],
  ["23f1", "⏱️", "Stopwatch", "travel"],
  ["23f2", "⏲️", "Timer clock", "travel"],
  ["1f570", "🕰️", "Mantelpiece clock", "travel"],
  ["1f55b", "🕛", "Twelve o’clock", "travel"],
  ["1f311", "🌑", "New moon", "travel"],
  ["1f312", "🌒", "Waxing crescent moon", "travel"],
  ["1f313", "🌓", "First quarter moon", "travel"],
  ["1f314", "🌔", "Waxing gibbous moon", "travel"],
  ["1f315", "🌕", "Full moon", "travel"],
  ["1f316", "🌖", "Waning gibbous moon", "travel"],
  ["1f317", "🌗", "Last quarter moon", "travel"],
  ["1f318", "🌘", "Waning crescent moon", "travel"],
  ["1f383", "🎃", "Jack-o-lantern", "activities"],
  ["1f384", "🎄", "Christmas tree", "activities"],
  ["1f386", "🎆", "Fireworks", "activities"],
  ["1f387", "🎇", "Sparkler", "activities"],
  ["1f9e8", "🧨", "Firecracker", "activities"],
  ["2728", "✨", "Sparkles", "activities"],
  ["1f388", "🎈", "Balloon", "activities"],
  ["1f389", "🎉", "Party popper", "activities"],
  ["1f38a", "🎊", "Confetti ball", "activities"],
  ["1f38b", "🎋", "Tanabata tree", "activities"],
  ["1f396", "🎖️", "Military medal", "activities"],
  ["1f3c6", "🏆", "Trophy", "activities"],
  ["1f3c5", "🏅", "Sports medal", "activities"],
  ["1f947", "🥇", "1st place medal", "activities"],
  ["1f948", "🥈", "2nd place medal", "activities"],
  ["1f949", "🥉", "3rd place medal", "activities"],
  ["26bd", "⚽", "Soccer ball", "activities"],
  ["26be", "⚾", "Baseball", "activities"],
  ["1f94e", "🥎", "Softball", "activities"],
  ["1f3c0", "🏀", "Basketball", "activities"],
  ["1f3d0", "🏐", "Volleyball", "activities"],
  ["1f3c8", "🏈", "American football", "activities"],
  ["1f3c9", "🏉", "Rugby football", "activities"],
  ["1f3be", "🎾", "Tennis", "activities"],
  ["1f94f", "🥏", "Flying disc", "activities"],
  ["1f3b3", "🎳", "Bowling", "activities"],
  ["1f3af", "🎯", "Bullseye", "activities"],
  ["1fa80", "🪀", "Yo-yo", "activities"],
  ["1fa81", "🪁", "Kite", "activities"],
  ["1f52b", "🔫", "Water pistol", "activities"],
  ["1f3b1", "🎱", "Pool 8 ball", "activities"],
  ["1f52e", "🔮", "Crystal ball", "activities"],
  ["1fa84", "🪄", "Magic wand", "activities"],
  ["1f3ae", "🎮", "Video game", "activities"],
  ["1f579", "🕹️", "Joystick", "activities"],
  ["1f3b0", "🎰", "Slot machine", "activities"],
  ["1f3ad", "🎭", "Performing arts", "activities"],
  ["1f5bc", "🖼️", "Framed picture", "activities"],
  ["1f3a8", "🎨", "Artist palette", "activities"],
  ["1f9f5", "🧵", "Thread", "activities"],
  ["1faa1", "🪡", "Sewing needle", "activities"],
  ["1f9f6", "🧶", "Yarn", "activities"],
  ["1faa2", "🪢", "Knot", "activities"],
  ["1f453", "👓", "Glasses", "objects"],
  ["1f576", "🕶️", "Sunglasses", "objects"],
  ["1f97d", "🥽", "Goggles", "objects"],
  ["1f97c", "🥼", "Lab coat", "objects"],
  ["1f9ba", "🦺", "Safety vest", "objects"],
  ["1f454", "👔", "Necktie", "objects"],
  ["1f507", "🔇", "Muted speaker", "objects"],
  ["1f508", "🔈", "Speaker low volume", "objects"],
  ["1f509", "🔉", "Speaker medium volume", "objects"],
  ["1f50a", "🔊", "Speaker high volume", "objects"],
  ["1f4e2", "📢", "Loudspeaker", "objects"],
  ["1f4e3", "📣", "Megaphone", "objects"],
  ["1f3bc", "🎼", "Musical score", "objects"],
  ["1f3b5", "🎵", "Musical note", "objects"],
  ["1f3b6", "🎶", "Musical notes", "objects"],
  ["1f399", "🎙️", "Studio microphone", "objects"],
  ["1f39a", "🎚️", "Level slider", "objects"],
  ["1f39b", "🎛️", "Control knobs", "objects"],
  ["1f3b7", "🎷", "Saxophone", "objects"],
  ["1fa97", "🪗", "Accordion", "objects"],
  ["1f3b8", "🎸", "Guitar", "objects"],
  ["1f3b9", "🎹", "Musical keyboard", "objects"],
  ["1f3ba", "🎺", "Trumpet", "objects"],
  ["1f3bb", "🎻", "Violin", "objects"],
  ["1f50b", "🔋", "Battery", "objects"],
  ["1faab", "🪫", "Low battery", "objects"],
  ["1f50c", "🔌", "Electric plug", "objects"],
  ["1f4bb", "💻", "Laptop", "objects"],
  ["1f5a5", "🖥️", "Desktop computer", "objects"],
  ["1f5a8", "🖨️", "Printer", "objects"],
  ["1f3a5", "🎥", "Movie camera", "objects"],
  ["1f39e", "🎞️", "Film frames", "objects"],
  ["1f4fd", "📽️", "Film projector", "objects"],
  ["1f3ac", "🎬", "Clapper board", "objects"],
  ["1f4fa", "📺", "Television", "objects"],
  ["1f4f7", "📷", "Camera", "objects"],
  ["270f", "✏️", "Pencil", "objects"],
  ["2712", "✒️", "Black nib", "objects"],
  ["1f58b", "🖋️", "Fountain pen", "objects"],
  ["1f58a", "🖊️", "Pen", "objects"],
  ["1f58c", "🖌️", "Paintbrush", "objects"],
  ["1f58d", "🖍️", "Crayon", "objects"],
  ["1f528", "🔨", "Hammer", "objects"],
  ["1fa93", "🪓", "Axe", "objects"],
  ["26cf", "⛏️", "Pick", "objects"],
  ["2692", "⚒️", "Hammer and pick", "objects"],
  ["1f6e0", "🛠️", "Hammer and wrench", "objects"],
  ["1f5e1", "🗡️", "Dagger", "objects"],
  ["2697", "⚗️", "Alembic", "objects"],
  ["1f9ea", "🧪", "Test tube", "objects"],
  ["1f9eb", "🧫", "Petri dish", "objects"],
  ["1f9ec", "🧬", "Dna", "objects"],
  ["1f52c", "🔬", "Microscope", "objects"],
  ["1f52d", "🔭", "Telescope", "objects"],
  ["1f6ac", "🚬", "Cigarette", "objects"],
  ["26b0", "⚰️", "Coffin", "objects"],
  ["1faa6", "🪦", "Headstone", "objects"],
  ["26b1", "⚱️", "Funeral urn", "objects"],
  ["1f9ff", "🧿", "Nazar amulet", "objects"],
  ["1faac", "🪬", "Hamsa", "objects"],
  ["2b06", "⬆️", "Up arrow", "symbols"],
  ["2197", "↗️", "Up-right arrow", "symbols"],
  ["27a1", "➡️", "Right arrow", "symbols"],
  ["2198", "↘️", "Down-right arrow", "symbols"],
  ["2b07", "⬇️", "Down arrow", "symbols"],
  ["2199", "↙️", "Down-left arrow", "symbols"],
  ["2b05", "⬅️", "Left arrow", "symbols"],
  ["2196", "↖️", "Up-left arrow", "symbols"],
  ["2195", "↕️", "Up-down arrow", "symbols"],
  ["2194", "↔️", "Left-right arrow", "symbols"],
  ["1f534", "🔴", "Red circle", "symbols"],
  ["1f7e0", "🟠", "Orange circle", "symbols"],
  ["1f7e1", "🟡", "Yellow circle", "symbols"],
  ["1f7e2", "🟢", "Green circle", "symbols"],
  ["1f535", "🔵", "Blue circle", "symbols"],
  ["1f7e3", "🟣", "Purple circle", "symbols"],
  ["1f7e4", "🟤", "Brown circle", "symbols"],
  ["26ab", "⚫", "Black circle", "symbols"],
  ["26aa", "⚪", "White circle", "symbols"],
  ["1f7e5", "🟥", "Red square", "symbols"],
  ["1f3c1", "🏁", "Chequered flag", "flags"],
  ["1f6a9", "🚩", "Triangular flag", "flags"],
  ["1f38c", "🎌", "Crossed flags", "flags"],
  ["1f3f4", "🏴", "Black flag", "flags"],
  ["1f3f3", "🏳️", "White flag", "flags"],
];

export const EMOJI: Emoji[] = LIST.flatMap(([code, char, name, group]) => {
  const svg = FILES[`../assets/emoji/${code}.svg`];
  return svg ? [{ code, char, name, group, svg }] : [];
});

const urls = new Map<string, string>();

/** A data URL for showing the emoji in the UI. */
export function emojiUrl(e: Emoji): string {
  let u = urls.get(e.code);
  if (!u) {
    u = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(e.svg)}`;
    urls.set(e.code, u);
  }
  return u;
}

export const emojiByChar = (char: string | undefined): Emoji | undefined => (char ? EMOJI.find((e) => e.char === char) : undefined);
