import { type Port, pick, type Rival, rival, trim } from "./kit";

// ------------------------------------------------------------------ 2007

// Side ports only, so every layout takes them.
const PORTS: Port[] = [
  ["dc-jack", "left"],
  ["vga", "left"],
  ["usb-a-2.0", "left"],
  ["expresscard-54", "left"],
  ["ethernet-1g", "right"],
  ["modem-rj11", "right"],
  ["usb-a-2.0", "right"],
  ["usb-a-2.0", "right"],
  ["headphone-mic", "right"],
];
const PORTS_BIZ: Port[] = [
  ["dc-jack", "left"],
  ["vga", "left"],
  ["usb-a-2.0", "left"],
  ["expresscard-54", "left"],
  ["ethernet-1g", "left"],
  ["modem-rj11", "left"],
  ["usb-a-2.0", "right"],
  ["usb-a-2.0", "right"],
  ["firewire-400", "right"],
  ["headphone-mic", "right"],
  ["lock-slot", "right"],
];
const PORTS_SMALL: Port[] = [
  ["dc-jack", "left"],
  ["vga", "left"],
  ["usb-a-2.0", "left"],
  ["ethernet-1g", "right"],
  ["usb-a-2.0", "right"],
  ["sd-reader", "right"],
  ["headphone-mic", "right"],
];
const PORTS_MEDIA: Port[] = [
  ["dc-jack", "left"],
  ["vga", "left"],
  ["hdmi-1.3", "left"],
  ["usb-a-2.0", "left"],
  ["expresscard-54", "left"],
  ["ethernet-1g", "right"],
  ["firewire-400", "right"],
  ["usb-a-2.0", "right"],
  ["usb-a-2.0", "right"],
  ["sd-reader", "right"],
  ["headphone-mic", "right"],
];
const PORTS_MAC: Port[] = [
  ["dc-jack", "left"],
  ["ethernet-1g", "left"],
  ["dvi-d", "left"],
  ["firewire-400", "left"],
  ["usb-a-2.0", "left"],
  ["usb-a-2.0", "left"],
  ["headphone-mic", "left"],
];
const PORTS_MAC_PRO: Port[] = [
  ["dc-jack", "left"],
  ["ethernet-1g", "left"],
  ["firewire-400", "left"],
  ["usb-a-2.0", "left"],
  ["headphone-mic", "left"],
  ["expresscard-34", "right"],
  ["usb-a-2.0", "right"],
  ["dvi-d", "right"],
];

const R: Rival[] = [
  rival(2007, "lenovo", "ThinkPad T61", {
    body: "workhorse",
    layout: "b",
    size: [311, 255, 28],
    price: 1349,
    parts: {
      processor: "core2-duo-t7300",
      memory: ["ddr2-667-sodimm", { capacity: 1, slots: 2 }],
      storage: ["hdd25-5400", { capacity: 120 }],
      display: "2006-14.1-1280x800-tn-matte",
      battery: ["li-ion-18650", { cells: 6 }],
      cooling: "one-fan",
      optical: "dvd-rw-slim-2006",
      wireless: ["wifi-n-draft", { bluetooth: "2.0" }],
      keyboard: ["kb-2.5", { light: "lid-light" }],
      trackpad: ["pad-65x40", { stick: "yes" }],
      speakers: "spk-stereo-2006",
    },
    ports: PORTS_BIZ,
    materials: { lid: "magnesium" },
  }),
  rival(2007, "lenovo", "ThinkPad T61 15.4", {
    body: "workhorse",
    layout: "b",
    size: [357, 262, 30],
    price: 1799,
    parts: {
      processor: "core2-duo-t7500",
      graphics: "geforce-8400m-gs",
      memory: ["ddr2-667-sodimm", { capacity: 2, slots: 2 }],
      storage: ["hdd25-7200", { capacity: 100 }],
      display: "2006-15.4-1680x1050-tn-matte",
      battery: ["li-ion-18650", { cells: 6 }],
      cooling: "one-fan",
      optical: "dvd-rw-slim-2006",
      wireless: ["wifi-n-draft", { bluetooth: "2.0" }],
      keyboard: ["kb-2.5", { light: "lid-light" }],
      trackpad: ["pad-65x40", { stick: "yes" }],
      speakers: "spk-stereo-2006",
    },
    ports: PORTS_BIZ,
    materials: { lid: "magnesium" },
  }),
  rival(2007, "lenovo", "ThinkPad X61s", {
    body: "workhorse",
    layout: "c",
    size: [268, 211, 21],
    price: 1599,
    parts: {
      processor: "core2-duo-l7500",
      memory: ["ddr2-667-sodimm", { capacity: 1, slots: 2 }],
      storage: ["hdd25-5400", { capacity: 80 }],
      display: "2006-12.1-1024x768-tn-matte",
      battery: ["li-ion-18650", { cells: 4 }],
      cooling: "one-fan",
      wireless: ["wifi-n-draft", { bluetooth: "2.0" }],
      keyboard: ["kb-2.5", { pitch: 17 }],
      trackpad: ["pad-65x40", { stick: "yes" }],
      speakers: "spk-mono",
    },
    ports: PORTS_SMALL,
    materials: { floor: "magnesium", deck: "magnesium", lid: "magnesium" },
    spend: { material: 0.5 },
  }),
  rival(2007, "lenovo", "IdeaPad Y510", {
    body: "workhorse",
    layout: "b",
    size: [358, 262, 30],
    price: 1199,
    parts: {
      processor: "core2-duo-t5450",
      graphics: "geforce-8600m-gs",
      memory: ["ddr2-667-sodimm", { capacity: 2, slots: 2 }],
      storage: ["hdd25-5400", { capacity: 160 }],
      display: "2006-15.4-1280x800-tn-glossy",
      battery: ["li-ion-18650", { cells: 6 }],
      cooling: "one-fan",
      optical: "dvd-rw-dl",
      wireless: ["wifi-abg", { bluetooth: "2.0" }],
      keyboard: "kb-3.0",
      trackpad: "pad-75x45",
      webcam: "cam-1.3mp",
      speakers: "spk-stereo-2006",
    },
    ports: [
      ["dc-jack", "left"],
      ["vga", "left"],
      ["hdmi-1.3", "left"],
      ["usb-a-2.0", "left"],
      ["expresscard-54", "left"],
      ["ethernet-1g", "left"],
      ["firewire-400", "right"],
      ["usb-a-2.0", "right"],
      ["usb-a-2.0", "right"],
      ["sd-reader", "right"],
      ["headphone-mic", "right"],
    ],
  }),
  rival(2007, "hp", "Compaq Presario V6000", {
    body: "pillow",
    layout: "b",
    size: [358, 262, 30],
    price: 849,
    parts: {
      processor: "mobile-sempron-3600",
      memory: ["ddr2-667-sodimm", { capacity: 0.5, slots: 1 }],
      storage: ["hdd25-5400", { capacity: 60 }],
      display: "2006-15.4-1280x800-tn-glossy",
      battery: ["li-ion-18650", { cells: 6 }],
      cooling: "one-fan",
      optical: "combo",
      wireless: "wifi-bg",
      keyboard: "kb-3.0",
      trackpad: "pad-75x45",
      speakers: "spk-stereo-2006",
    },
    ports: PORTS,
  }),
  rival(2007, "hp", "Pavilion dv6500", {
    body: "workhorse",
    layout: "b",
    size: [357, 257, 30],
    price: 1149,
    parts: {
      processor: "core2-duo-t5450",
      graphics: "geforce-8400m-gs",
      memory: ["ddr2-667-sodimm", { capacity: 1, slots: 2 }],
      storage: ["hdd25-5400", { capacity: 160 }],
      display: "2006-15.4-1280x800-tn-glossy",
      battery: ["li-ion-18650", { cells: 6 }],
      cooling: "one-fan",
      optical: "dvd-rw-dl",
      wireless: ["wifi-abg", { bluetooth: "2.0" }],
      keyboard: "kb-3.0",
      trackpad: "pad-75x45",
      webcam: "cam-1.3mp",
      speakers: "spk-stereo-2006",
    },
    ports: PORTS_MEDIA,
  }),
  rival(2007, "hp", "Pavilion dv9500", {
    body: "pillow",
    layout: "c",
    size: [395, 290, 36],
    price: 1399,
    parts: {
      processor: "core2-duo-t7300",
      graphics: "geforce-8600m-gs",
      memory: ["ddr2-667-sodimm", { capacity: 2, slots: 2 }],
      storage: [
        ["hdd25-5400", { capacity: 160 }],
        ["hdd25-5400", { capacity: 120 }],
      ],
      display: "2006-17-1440x900-tn-glossy",
      battery: ["li-ion-18650", { cells: 6 }],
      cooling: "one-fan",
      optical: "dvd-rw-dl",
      wireless: ["wifi-abg", { bluetooth: "2.0" }],
      keyboard: ["kb-3.0", { cols: 19 }],
      trackpad: "pad-75x45",
      webcam: "cam-1.3mp",
      speakers: "spk-stereo-sub",
    },
    ports: [
      ["dc-jack", "left"],
      ["vga", "left"],
      ["s-video", "left"],
      ["hdmi-1.3", "right"],
      ["ethernet-1g", "left"],
      ["usb-a-2.0", "right"],
      ["usb-a-2.0", "right"],
      ["usb-a-2.0", "right"],
      ["firewire-400", "front"],
      ["expresscard-54", "front"],
      ["headphone-mic", "right"],
    ],
  }),
  rival(2007, "hp", "Compaq 2510p", {
    body: "workhorse",
    layout: "c",
    size: [282, 214, 20],
    price: 1599,
    parts: {
      processor: "core2-duo-u7600",
      memory: ["ddr2-667-sodimm", { capacity: 1, slots: 1 }],
      storage: "hdd18",
      display: "2006-12.1-1280x800-tn-matte",
      battery: ["li-ion-18650", { cells: 6 }],
      cooling: "one-fan",
      wireless: ["wifi-abg", { bluetooth: "2.0" }],
      keyboard: ["kb-2.5", { pitch: 17 }],
      trackpad: ["pad-65x40", { stick: "yes" }],
      speakers: "spk-mono",
    },
    ports: PORTS_SMALL,
    materials: { floor: "magnesium", deck: "magnesium", lid: "magnesium" },
    spend: { material: 1, packing: 1, graphics: 1, battery: 1, storage: 1, cooling: 1, keyboard: 1, speakers: 1 },
  }),
  rival(2007, "dell", "XPS M1330", {
    body: "workhorse",
    layout: "c",
    size: [318, 238, 23],
    price: 1299,
    parts: {
      processor: "core2-duo-t7300",
      graphics: "geforce-8400m-gs",
      memory: ["ddr2-667-sodimm", { capacity: 2, slots: 2 }],
      storage: "hdd18",
      display: "2006-13.3-1280x800-tn-glossy",
      battery: ["li-ion-18650", { cells: 4 }],
      cooling: "one-fan",
      wireless: ["wifi-n-draft", { bluetooth: "2.0" }],
      keyboard: "kb-2.5",
      trackpad: "pad-65x40",
      webcam: "cam-0.3mp",
      speakers: "spk-stereo-2006",
    },
    ports: [...PORTS_SMALL, ["hdmi-1.3", "left"], ["expresscard-54", "left"]],
    materials: { lid: "aluminium" },
    spend: { material: 0.5, packing: 0.5 },
  }),
  rival(2007, "dell", "XPS M1210", {
    body: "workhorse",
    layout: "c",
    size: [297, 221, 20],
    price: 1349,
    parts: {
      processor: "core2-duo-t7200",
      graphics: "geforce-go-7400",
      memory: ["ddr2-667-sodimm", { capacity: 1, slots: 2 }],
      storage: "hdd18",
      display: "2006-12.1-1280x800-tn-glossy",
      battery: ["li-ion-18650", { cells: 4 }],
      cooling: "one-fan",
      wireless: ["wifi-abg", { bluetooth: "2.0" }],
      keyboard: "kb-2.5",
      trackpad: "pad-65x40",
      speakers: "spk-mono",
    },
    ports: PORTS_SMALL,
    materials: { floor: "magnesium", deck: "magnesium", lid: "magnesium" },
    spend: { material: 1, packing: 1, battery: 1, cooling: 1 },
  }),
  rival(2007, "dell", "XPS M1530", {
    body: "workhorse",
    layout: "b",
    size: [357, 258, 30],
    price: 1499,
    parts: {
      processor: "core2-duo-t7500",
      graphics: "geforce-8600m-gt",
      memory: ["ddr2-667-sodimm", { capacity: 2, slots: 2 }],
      storage: ["hdd25-5400", { capacity: 160 }],
      display: "2006-15.4-1440x900-tn-glossy",
      battery: ["li-ion-18650", { cells: 6 }],
      cooling: "one-fan",
      optical: "dvd-rw-slim-2006",
      wireless: ["wifi-n-draft", { bluetooth: "2.0" }],
      keyboard: "kb-2.5",
      trackpad: "pad-75x45",
      webcam: "cam-1.3mp",
      speakers: "spk-stereo-2006",
    },
    ports: [
      ["dc-jack", "left"],
      ["vga", "left"],
      ["hdmi-1.3", "left"],
      ["usb-a-2.0", "left"],
      ["expresscard-54", "left"],
      ["ethernet-1g", "left"],
      ["firewire-400", "right"],
      ["usb-a-2.0", "right"],
      ["usb-a-2.0", "right"],
      ["sd-reader", "right"],
      ["headphone-mic", "right"],
    ],
    materials: { lid: "aluminium" },
  }),
  rival(2007, "dell", "XPS M1730", {
    body: "pillow",
    layout: "c",
    size: [406, 303, 45],
    price: 3499,
    parts: {
      processor: "core2-extreme-x7900",
      graphics: "geforce-8800m-gtx",
      memory: ["ddr2-667-sodimm", { capacity: 2, slots: 2 }],
      storage: [
        ["hdd25-7200", { capacity: 100 }],
        ["hdd25-7200", { capacity: 100 }],
      ],
      display: "2006-17-1920x1200-tn-glossy",
      battery: ["li-ion-18650", { cells: 9 }],
      cooling: "two-fans",
      optical: "dvd-rw-dl",
      wireless: ["wifi-n-draft", { bluetooth: "2.0" }],
      keyboard: ["kb-3.0", { cols: 19, light: "backlit" }],
      trackpad: "pad-85x50",
      webcam: "cam-1.3mp",
      speakers: "spk-stereo-sub",
    },
    ports: [
      ["dc-jack", "left"],
      ["vga", "left"],
      ["s-video", "front"],
      ["hdmi-1.3", "left"],
      ["ethernet-1g", "left"],
      ["usb-a-2.0", "right"],
      ["usb-a-2.0", "right"],
      ["usb-a-2.0", "right"],
      ["firewire-400", "right"],
      ["expresscard-54", "front"],
      ["headphone-mic", "right"],
    ],
    spend: { packing: 0.5 },
  }),
  rival(2007, "dell", "Alienware m15x", {
    body: "workhorse",
    layout: "b",
    size: [357, 267, 30],
    price: 2499,
    parts: {
      processor: "core2-duo-t7700",
      graphics: "geforce-8800m-gts",
      memory: ["ddr2-667-sodimm", { capacity: 2, slots: 2 }],
      storage: ["hdd25-7200", { capacity: 100 }],
      display: "2006-15.4-1920x1200-tn-matte",
      battery: ["li-ion-18650", { cells: 6 }],
      cooling: "two-fans",
      optical: "dvd-rw-slim-2006",
      wireless: ["wifi-n-draft", { bluetooth: "2.0" }],
      keyboard: ["kb-2.5", { light: "backlit" }],
      trackpad: "pad-75x45",
      webcam: "cam-1.3mp",
      speakers: "spk-stereo-2006",
    },
    ports: PORTS_MEDIA,
    materials: { lid: "magnesium" },
  }),
  rival(2007, "dell", "Latitude D630", {
    body: "workhorse",
    layout: "b",
    size: [337, 238, 26],
    price: 1299,
    parts: {
      processor: "core2-duo-t7300",
      memory: ["ddr2-667-sodimm", { capacity: 1, slots: 2 }],
      storage: ["hdd25-5400", { capacity: 80 }],
      display: "2006-14.1-1440x900-tn-glossy",
      battery: ["li-ion-18650", { cells: 6 }],
      cooling: "one-fan",
      optical: "dvd-rw-slim-2006",
      wireless: ["wifi-abg", { bluetooth: "2.0" }],
      keyboard: "kb-2.5",
      trackpad: ["pad-65x40", { stick: "yes" }],
      speakers: "spk-mono",
    },
    ports: PORTS_BIZ,
    materials: { lid: "magnesium" },
  }),
  rival(2007, "dell", "Inspiron 1720", {
    body: "pillow",
    layout: "c",
    size: [393, 287, 38],
    price: 1299,
    parts: {
      processor: "core2-duo-t7300",
      graphics: "geforce-8600m-gt",
      memory: ["ddr2-667-sodimm", { capacity: 2, slots: 2 }],
      storage: ["hdd25-5400", { capacity: 160 }],
      display: "2006-17-1440x900-tn-glossy",
      battery: ["li-ion-18650", { cells: 6 }],
      cooling: "one-fan",
      optical: "dvd-rw-dl",
      wireless: ["wifi-abg", { bluetooth: "2.0" }],
      keyboard: ["kb-3.0", { cols: 19 }],
      trackpad: "pad-75x45",
      webcam: "cam-1.3mp",
      speakers: "spk-stereo-2006",
    },
    ports: [
      ["dc-jack", "left"],
      ["vga", "left"],
      ["dvi-d", "left"],
      ["s-video", "left"],
      ["hdmi-1.3", "left"],
      ["ethernet-1g", "left"],
      ["usb-a-2.0", "right"],
      ["usb-a-2.0", "right"],
      ["usb-a-2.0", "right"],
      ["firewire-400", "right"],
      ["expresscard-54", "front"],
      ["headphone-mic", "right"],
    ],
  }),
  rival(2007, "apple", "MacBook (Late 2007)", {
    body: "workhorse",
    layout: "b",
    size: [325, 227, 28],
    price: 1099,
    parts: {
      processor: "core2-duo-t7300",
      memory: ["ddr2-667-sodimm", { capacity: 1, slots: 2 }],
      storage: ["hdd25-5400", { capacity: 80 }],
      display: "2006-13.3-1280x800-tn-glossy",
      battery: ["slim-li-po-2006", { wh: 40 }],
      cooling: "one-fan",
      optical: "combo",
      wireless: ["wifi-n-draft", { bluetooth: "2.0" }],
      keyboard: "kb-2.5",
      trackpad: "pad-75x45",
      webcam: "cam-0.3mp",
      speakers: "spk-stereo-2006",
    },
    ports: PORTS_MAC,
    spend: { material: 0.5, packing: 0.5 },
  }),
  rival(2007, "apple", "MacBook Pro 15 (Mid 2007)", {
    body: "workhorse",
    layout: "b",
    size: [357, 243, 26],
    price: 1999,
    parts: {
      processor: "core2-duo-t7500",
      graphics: "geforce-8600m-gt",
      memory: ["ddr2-667-sodimm", { capacity: 2, slots: 2 }],
      storage: ["hdd25-5400", { capacity: 120 }],
      display: "2006-15.4-1440x900-tn-glossy",
      battery: ["li-ion-18650", { cells: 6 }],
      cooling: "two-fans",
      optical: "dvd-rw-slim-2006",
      wireless: ["wifi-n-draft", { bluetooth: "2.0" }],
      keyboard: ["kb-2.5", { light: "backlit" }],
      trackpad: "pad-85x50",
      webcam: "cam-0.3mp",
      speakers: "spk-stereo-2006",
    },
    ports: PORTS_MAC_PRO,
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
    spend: { material: 1, packing: 1, battery: 1, cooling: 1 },
  }),
  rival(2007, "apple", "MacBook Pro 17 (Mid 2007)", {
    body: "workhorse",
    layout: "c",
    size: [393, 266, 26],
    price: 2799,
    parts: {
      processor: "core2-duo-t7700",
      graphics: "geforce-8600m-gt",
      memory: ["ddr2-667-sodimm", { capacity: 2, slots: 2 }],
      storage: ["hdd25-5400", { capacity: 160 }],
      display: "2006-17-1680x1050-tn-glossy",
      battery: ["li-ion-18650", { cells: 9 }],
      cooling: "two-fans",
      optical: "dvd-rw-slim-2006",
      wireless: ["wifi-n-draft", { bluetooth: "2.0" }],
      keyboard: ["kb-2.5", { light: "backlit" }],
      trackpad: "pad-85x50",
      webcam: "cam-0.3mp",
      speakers: "spk-stereo-2006",
    },
    ports: [
      ["dc-jack", "left"],
      ["ethernet-1g", "left"],
      ["firewire-400", "left"],
      ["usb-a-2.0", "left"],
      ["headphone-mic", "left"],
      ["expresscard-34", "front"],
      ["usb-a-2.0", "left"],
      ["dvi-d", "right"],
      ["usb-a-2.0", "right"],
      ["firewire-400", "right"],
    ],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
    spend: { material: 1, packing: 1, battery: 1, cooling: 1 },
  }),
  rival(2007, "asus", "G1S", {
    body: "workhorse",
    layout: "b",
    size: [362, 268, 26],
    price: 1699,
    parts: {
      processor: "core2-duo-t7500",
      graphics: "geforce-8600m-gt",
      memory: ["ddr2-667-sodimm", { capacity: 2, slots: 2 }],
      storage: ["hdd25-7200", { capacity: 100 }],
      display: "2006-15.4-1680x1050-tn-glossy",
      battery: ["li-ion-18650", { cells: 6 }],
      cooling: "two-fans",
      optical: "dvd-rw-slim-2006",
      wireless: ["wifi-n-draft", { bluetooth: "2.0" }],
      keyboard: ["kb-3.0", { light: "backlit" }],
      trackpad: "pad-75x45",
      webcam: "cam-1.3mp",
      speakers: "spk-stereo-2006",
    },
    ports: [
      ["dc-jack", "left"],
      ["vga", "left"],
      ["dvi-d", "left"],
      ["s-video", "front"],
      ["hdmi-1.3", "left"],
      ["ethernet-1g", "left"],
      ["usb-a-2.0", "right"],
      ["usb-a-2.0", "right"],
      ["usb-a-2.0", "right"],
      ["firewire-400", "right"],
      ["expresscard-54", "right"],
      ["headphone-mic", "front"],
    ],
  }),
  rival(2007, "asus", "G2S", {
    body: "pillow",
    layout: "c",
    size: [398, 290, 38],
    price: 1899,
    parts: {
      processor: "core2-duo-t7500",
      graphics: "geforce-8600m-gt",
      memory: ["ddr2-667-sodimm", { capacity: 2, slots: 2 }],
      storage: ["hdd25-7200", { capacity: 100 }],
      display: "2006-17-1920x1200-tn-glossy",
      battery: ["li-ion-18650", { cells: 9 }],
      cooling: "two-fans",
      optical: "dvd-rw-dl",
      wireless: ["wifi-n-draft", { bluetooth: "2.0" }],
      keyboard: ["kb-3.0", { cols: 19, light: "backlit" }],
      trackpad: "pad-85x50",
      webcam: "cam-1.3mp",
      speakers: "spk-stereo-sub",
    },
    ports: [
      ["dc-jack", "left"],
      ["vga", "left"],
      ["dvi-d", "left"],
      ["s-video", "left"],
      ["hdmi-1.3", "left"],
      ["ethernet-1g", "left"],
      ["usb-a-2.0", "right"],
      ["usb-a-2.0", "right"],
      ["usb-a-2.0", "right"],
      ["firewire-400", "right"],
      ["expresscard-54", "front"],
      ["headphone-mic", "right"],
    ],
  }),
  rival(2007, "asus", "G2P", {
    body: "pillow",
    layout: "c",
    size: [398, 290, 38],
    price: 2199,
    parts: {
      processor: "core2-duo-t7600",
      graphics: "geforce-go-7950-gtx",
      memory: ["ddr2-667-sodimm", { capacity: 2, slots: 2 }],
      storage: ["hdd25-7200", { capacity: 100 }],
      display: "2006-17-1920x1200-tn-glossy",
      battery: ["li-ion-18650", { cells: 9 }],
      cooling: "two-fans",
      optical: "dvd-rw-dl",
      wireless: ["wifi-abg", { bluetooth: "2.0" }],
      keyboard: ["kb-3.0", { cols: 19, light: "backlit" }],
      trackpad: "pad-85x50",
      webcam: "cam-1.3mp",
      speakers: "spk-stereo-sub",
    },
    ports: [
      ["dc-jack", "left"],
      ["vga", "left"],
      ["dvi-d", "left"],
      ["s-video", "left"],
      ["hdmi-1.3", "left"],
      ["ethernet-1g", "left"],
      ["usb-a-2.0", "right"],
      ["usb-a-2.0", "right"],
      ["usb-a-2.0", "right"],
      ["firewire-400", "right"],
      ["expresscard-54", "front"],
      ["headphone-mic", "right"],
    ],
  }),
  rival(2007, "asus", "U3S", {
    body: "workhorse",
    layout: "c",
    size: [310, 225, 20],
    price: 1499,
    parts: {
      processor: "core2-duo-t7300",
      graphics: "geforce-8400m-g",
      memory: ["ddr2-667-sodimm", { capacity: 1, slots: 2 }],
      storage: "hdd18",
      display: "2006-13.3-1280x800-tn-glossy",
      battery: ["li-ion-18650", { cells: 4 }],
      cooling: "one-fan",
      wireless: ["wifi-n-draft", { bluetooth: "2.0" }],
      keyboard: "kb-2.5",
      trackpad: "pad-65x40",
      speakers: "spk-mono",
    },
    ports: PORTS_SMALL,
    materials: { floor: "magnesium", deck: "magnesium", lid: "cfrp" },
    spend: { material: 1, packing: 1, graphics: 1, battery: 1, storage: 1, cooling: 1, keyboard: 1, speakers: 1 },
  }),
  rival(2007, "acer", "Aspire 4520", {
    body: "workhorse",
    layout: "b",
    size: [342, 247, 33],
    price: 849,
    parts: {
      processor: "athlon64-x2-tk53",
      memory: ["ddr2-667-sodimm", { capacity: 0.5, slots: 1 }],
      storage: ["hdd25-5400", { capacity: 80 }],
      display: "2006-14.1-1280x800-tn-glossy",
      battery: ["li-ion-18650", { cells: 6 }],
      cooling: "one-fan",
      optical: "combo",
      wireless: "wifi-bg",
      keyboard: "kb-3.0",
      trackpad: "pad-65x40",
      speakers: "spk-stereo-2006",
    },
    ports: [
      ["dc-jack", "left"],
      ["vga", "left"],
      ["usb-a-2.0", "left"],
      ["expresscard-54", "left"],
      ["ethernet-1g", "right"],
      ["modem-rj11", "right"],
      ["usb-a-2.0", "left"],
      ["usb-a-2.0", "right"],
      ["headphone-mic", "right"],
    ],
  }),
  rival(2007, "acer", "Aspire 5920G", {
    body: "workhorse",
    layout: "b",
    size: [358, 267, 30],
    price: 1299,
    parts: {
      processor: "core2-duo-t7300",
      graphics: "geforce-8600m-gt",
      memory: ["ddr2-667-sodimm", { capacity: 2, slots: 2 }],
      storage: ["hdd25-5400", { capacity: 160 }],
      display: "2006-15.4-1280x800-tn-glossy",
      battery: ["li-ion-18650", { cells: 6 }],
      cooling: "one-fan",
      optical: "dvd-rw-dl",
      wireless: ["wifi-n-draft", { bluetooth: "2.0" }],
      keyboard: "kb-3.0",
      trackpad: "pad-75x45",
      webcam: "cam-1.3mp",
      speakers: "spk-stereo-2006",
    },
    ports: PORTS_MEDIA,
  }),
  rival(2007, "acer", "Aspire 7720G", {
    body: "pillow",
    layout: "c",
    size: [396, 290, 38],
    price: 1099,
    parts: {
      processor: "core2-duo-t5450",
      graphics: "geforce-8400m-gs",
      memory: ["ddr2-667-sodimm", { capacity: 1, slots: 2 }],
      storage: ["hdd25-5400", { capacity: 160 }],
      display: "2006-17-1440x900-tn-glossy",
      battery: ["li-ion-18650", { cells: 6 }],
      cooling: "one-fan",
      optical: "dvd-rw-dl",
      wireless: ["wifi-abg", { bluetooth: "2.0" }],
      keyboard: ["kb-3.0", { cols: 19 }],
      trackpad: "pad-75x45",
      webcam: "cam-1.3mp",
      speakers: "spk-stereo-2006",
    },
    ports: [
      ["dc-jack", "left"],
      ["vga", "left"],
      ["dvi-d", "left"],
      ["s-video", "left"],
      ["hdmi-1.3", "left"],
      ["ethernet-1g", "left"],
      ["usb-a-2.0", "right"],
      ["usb-a-2.0", "right"],
      ["usb-a-2.0", "right"],
      ["firewire-400", "right"],
      ["expresscard-54", "front"],
      ["headphone-mic", "right"],
    ],
  }),
  rival(2007, "acer", "Ferrari 5000", {
    body: "workhorse",
    layout: "b",
    size: [358, 267, 32],
    price: 1799,
    parts: {
      processor: "turion64-x2-tl66",
      graphics: "radeon-hd-2600",
      memory: ["ddr2-667-sodimm", { capacity: 2, slots: 2 }],
      storage: ["hdd25-5400", { capacity: 160 }],
      display: "2006-15.4-1680x1050-tn-glossy",
      battery: ["li-ion-18650", { cells: 6 }],
      cooling: "one-fan",
      optical: "dvd-rw-slim-2006",
      wireless: ["wifi-n-draft", { bluetooth: "2.0" }],
      keyboard: "kb-2.5",
      trackpad: "pad-75x45",
      webcam: "cam-1.3mp",
      speakers: "spk-stereo-2006",
    },
    ports: [
      ["dc-jack", "left"],
      ["vga", "left"],
      ["hdmi-1.3", "left"],
      ["usb-a-2.0", "left"],
      ["expresscard-54", "left"],
      ["ethernet-1g", "left"],
      ["firewire-400", "right"],
      ["usb-a-2.0", "right"],
      ["usb-a-2.0", "right"],
      ["sd-reader", "right"],
      ["headphone-mic", "right"],
    ],
    materials: { lid: "cfrp" },
  }),
];

const b = (n: string) => pick(R, n);

const T: Rival[] = [
  // Thin and light.
  trim(b("ThinkPad X61s"), "ThinkPad X61", 1199, {
    parts: { processor: "core2-duo-t7100" },
  }),
  trim(b("Compaq 2510p"), "Compaq 2510p (U7500)", 1349, {
    parts: { processor: "core2-duo-u7500" },
  }),
  trim(b("XPS M1210"), "XPS M1210 (HD 2600)", 1449, {
    parts: { graphics: "radeon-hd-2600" },
  }),
  trim(b("XPS M1210"), "XPS M1210 (T7700, 8600M GT)", 1799, {
    parts: { graphics: "geforce-8600m-gt", processor: "core2-duo-t7700" },
  }),
  trim(b("U3S"), "U3S (8600M GT)", 1549, {
    parts: { graphics: "geforce-8600m-gt" },
  }),
  trim(b("U3S"), "U3S (T7700, 8600M GT)", 1899, {
    parts: { graphics: "geforce-8600m-gt", processor: "core2-duo-t7700" },
  }),
  trim(b("XPS M1210"), "XPS M1210 (Go 7950 GTX)", 2499, {
    parts: { graphics: "geforce-go-7950-gtx", processor: "core2-duo-t7700" },
    spend: { material: 1, packing: 1, graphics: 1, battery: 1, storage: 1, cooling: 1, keyboard: 1, speakers: 1 },
  }),
  trim(b("U3S"), "U3S (Go 7950 GTX)", 2399, {
    parts: { graphics: "geforce-go-7950-gtx", battery: ["li-ion-18650", { cells: 4 }] },
    materials: { lid: "magnesium" },
  }),
  // Medium.
  trim(b("ThinkPad T61"), "ThinkPad R61 (Celeron 540)", 849, {
    parts: {
      processor: "celeron-540",
      optical: "combo",
      wireless: "wifi-bg",
      keyboard: "kb-2.5",
      memory: ["ddr2-667-sodimm", { capacity: 1, slots: 1 }],
      storage: ["hdd25-5400", { capacity: 80 }],
    },
    materials: { lid: "plastic" },
  }),
  trim(b("Aspire 4520"), "Aspire 4315", 799, {
    parts: {
      processor: "celeron-540",
      memory: ["ddr2-667-sodimm", { capacity: 0.5, slots: 1 }],
      storage: ["hdd25-5400", { capacity: 60 }],
    },
  }),
  trim(b("ThinkPad T61 15.4"), "ThinkPad T61p", 2399, {
    parts: {
      graphics: "geforce-8600m-gt",
      processor: "core2-duo-t7700",
      display: "2006-15.4-1920x1200-tn-matte",
    },
  }),
  trim(b("Latitude D630"), "Latitude D830", 1749, {
    parts: {
      processor: "core2-duo-t7500",
      display: "2006-15.4-1680x1050-tn-matte",
      graphics: "geforce-8400m-gs",
    },
  }),
  trim(b("MacBook (Late 2007)"), "MacBook (Late 2007, black)", 1499, {
    parts: {
      processor: "core2-duo-t7500",
      optical: "dvd-rw-slim-2006",
      storage: ["hdd25-5400", { capacity: 160 }],
    },
  }),
  trim(b("MacBook Pro 15 (Mid 2007)"), "MacBook Pro 15 (Mid 2007, 2.4 GHz)", 2499, {
    parts: { processor: "core2-duo-t7700", storage: ["hdd25-5400", { capacity: 160 }] },
  }),
  trim(b("XPS M1530"), "Inspiron 1520", 1199, {
    parts: { processor: "core2-duo-t5450", optical: "dvd-rw-dl" },
    materials: { lid: "plastic" },
  }),
  trim(b("XPS M1530"), "Inspiron 1520 (Celeron 540)", 849, {
    parts: {
      processor: "celeron-540",
      graphics: null,
      optical: "combo",
      memory: ["ddr2-667-sodimm", { capacity: 1, slots: 1 }],
      storage: ["hdd25-5400", { capacity: 80 }],
      webcam: null,
      wireless: "wifi-bg",
      display: "2006-15.4-1280x800-tn-glossy",
    },
    materials: { lid: "plastic" },
  }),
  trim(b("G1S"), "G1S (T5450, Go 7950 GTX)", 1549, {
    parts: { graphics: "geforce-go-7950-gtx", processor: "core2-duo-t5450" },
  }),
  trim(b("Alienware m15x"), "Alienware m15x (T5450)", 1549, {
    parts: { processor: "core2-duo-t5450", display: "2006-15.4-1280x800-tn-glossy" },
  }),
  trim(b("G1S"), "G1S (T7700, 8800M GTS)", 2299, {
    parts: { graphics: "geforce-8800m-gts", processor: "core2-duo-t7700" },
  }),
  // Large.
  trim(b("Aspire 7720G"), "Aspire 7720", 869, {
    parts: {
      graphics: null,
      processor: "celeron-540",
      memory: ["ddr2-667-sodimm", { capacity: 0.5, slots: 1 }],
      storage: ["hdd25-5400", { capacity: 80 }],
      optical: "combo",
      webcam: null,
      wireless: "wifi-bg",
    },
  }),
  trim(b("Aspire 7720G"), "Aspire 7720G (HD 2600)", 1199, {
    parts: { graphics: "radeon-hd-2600" },
  }),
  trim(b("Pavilion dv9500"), "Pavilion dv9700 (8600M GT)", 1449, {
    parts: { graphics: "geforce-8600m-gt" },
  }),
  trim(b("Inspiron 1720"), "Precision M6300", 2699, {
    parts: {
      graphics: "geforce-8700m-gt",
      processor: "core2-duo-t7700",
      display: "2006-17-1920x1200-tn-matte",
    },
    materials: { lid: "magnesium" },
  }),
  trim(b("Aspire 5920G"), "Aspire 5920G (8800M GTS)", 1499, {
    parts: { graphics: "geforce-8800m-gts", cooling: "two-fans" },
  }),
  trim(b("Aspire 7720G"), "Aspire 7720G (8800M GTS)", 1399, {
    parts: { graphics: "geforce-8800m-gts", cooling: "two-fans" },
  }),
  trim(b("G2P"), "G2P (T5600)", 1549, {
    parts: {
      processor: "core2-duo-t5600",
      memory: ["ddr2-667-sodimm", { capacity: 1, slots: 2 }],
    },
  }),
];

export const F2007: Rival[] = [...R, ...T];
