import { pick, type Port, type Rival, rival, trim } from "./kit";

// ------------------------------------------------------------------ 2025

const tb = (list: Port[], to: string): Port[] =>
  list.map(([id, side]) => [id === "thunderbolt-4" ? to : id, side]);

const PORTS: Port[] = [
  ["thunderbolt-4", "left"],
  ["thunderbolt-4", "left"],
  ["hdmi-2.1", "left"],
  ["usb-a-5g", "right"],
  ["audio-combo", "right"],
];
const PORTS_AMD = tb(PORTS, "usb4-40g");
const PORTS_THIN: Port[] = [
  ["thunderbolt-4", "left"],
  ["thunderbolt-4", "left"],
  ["audio-combo", "right"],
];
const PORTS_GAMING: Port[] = [
  ["usb-a-10g", "left"],
  ["usb-c-10g", "left"],
  ["audio-combo", "left"],
  ["dc-jack", "rear"],
  ["hdmi-2.1", "rear"],
  ["ethernet-2.5g", "rear"],
  ["thunderbolt-4", "rear"],
  ["usb-a-10g", "right"],
];
const PORTS_GAMING_AMD = tb(PORTS_GAMING, "usb4-40g");
const PORTS_BUDGET: Port[] = [
  ["dc-jack", "left"],
  ["hdmi-2.1", "left"],
  ["usb-a-5g", "left"],
  ["usb-c-10g", "left"],
  ["usb-a-5g", "right"],
  ["audio-combo", "right"],
];

const PORTS_MAC_AIR: Port[] = [
  ["dc-jack", "left"],
  ["usb4-40g", "left"],
  ["usb4-40g", "left"],
  ["audio-combo", "right"],
];
const PORTS_MAC_PRO: Port[] = [
  ["dc-jack", "left"],
  ["usb4-40g", "left"],
  ["usb4-40g", "left"],
  ["audio-combo", "left"],
  ["usb4-40g", "right"],
  ["hdmi-2.1", "right"],
  ["sd-reader-uhs2", "right"],
];

const R: Rival[] = [
  // ------------------------------------------------ lenovo
  rival(2025, "lenovo", "ThinkPad X1 Carbon Gen 13", {
    body: "workhorse",
    layout: "a",
    size: [315, 218, 11],
    price: 1999,
    parts: {
      processor: "core-ultra7-258v",
      memory: "lpddr5x-on-package",
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-14-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 60, thickness: "slim" }],
      cooling: "one-fan",
      wireless: "wifi-7",
      keyboard: ["kb-1.5", { light: "white" }],
      trackpad: ["pad-110x70", { mechanism: "mechanical", buttons: "separate", stick: "yes" }],
      webcam: "cam-5mp-ir",
      speakers: "spk-quad",
    },
    ports: [...PORTS, ["usb-a-5g", "left"]],
    materials: { floor: "magnesium", deck: "magnesium", lid: "cfrp" },
  }),
  rival(2025, "lenovo", "ThinkPad T14 Gen 6", {
    body: "workhorse",
    layout: "a",
    size: [314, 220, 14.5],
    price: 1399,
    parts: {
      processor: "core-ultra5-225u",
      memory: ["ddr5-5600-sodimm", { capacity: 16, slots: 1 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-14-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 60, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-7",
      keyboard: ["kb-1.5", { light: "white" }],
      trackpad: ["pad-110x70", { mechanism: "mechanical", buttons: "separate", stick: "yes" }],
      webcam: "cam-1080p-ir",
      speakers: "spk-stereo-2026",
    },
    ports: [...PORTS, ["usb-a-5g", "left"], ["ethernet-1g", "right"]],
    materials: { lid: "aluminium" },
  }),
  rival(2025, "lenovo", "ThinkPad E16 Gen 3 AMD", {
    body: "workhorse",
    layout: "a",
    size: [356, 249, 17],
    price: 999,
    parts: {
      processor: "ryzen5-220",
      memory: ["ddr5-5600-sodimm", { capacity: 16, slots: 2 }],
      storage: ["m2-2242-g4", { capacity: 512 }],
      display: "2021-16-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "white" }],
      trackpad: "pad-110x70",
      webcam: "cam-1080p",
      speakers: "spk-stereo-2026",
    },
    ports: [...PORTS_AMD, ["ethernet-1g", "right"]],
    materials: { lid: "aluminium" },
  }),
  rival(2025, "lenovo", "ThinkPad P16s Gen 4 AMD", {
    body: "workhorse",
    layout: "a",
    size: [361, 249, 17],
    price: 1449,
    parts: {
      processor: "ryzen-ai7-pro-360",
      memory: ["lpddr5x-soldered", { capacity: 32 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-16-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 60, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-7",
      keyboard: ["kb-1.5", { cols: 19, light: "white" }],
      trackpad: ["pad-110x70", { mechanism: "mechanical", buttons: "separate", stick: "yes" }],
      webcam: "cam-1080p-ir",
      speakers: "spk-stereo-2026",
    },
    ports: [...PORTS_AMD, ["ethernet-1g", "right"]],
    materials: { floor: "magnesium", lid: "aluminium" },
  }),
  rival(2025, "lenovo", "Yoga Slim 7x", {
    body: "blade",
    layout: "a",
    size: [313, 219, 11],
    price: 1099,
    parts: {
      processor: "snapdragon-x1e-78-100",
      memory: ["lpddr5x-soldered", { capacity: 16 }],
      storage: ["m2-2242-g4", { capacity: 512 }],
      display: ["2021-14-2880x1800-oled", { refresh: 90 }],
      battery: ["li-po-pouch", { wh: 75, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-7",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p-ir",
      speakers: "spk-quad",
    },
    ports: [
      ["usb4-40g", "left"],
      ["usb4-40g", "left"],
      ["usb4-40g", "right"],
    ],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2025, "lenovo", "LOQ 15IAX10", {
    body: "workhorse",
    layout: "a",
    size: [360, 265, 22],
    price: 1299,
    parts: {
      processor: "core5-210h",
      graphics: "rtx-5050-laptop",
      memory: ["ddr5-5600-sodimm", { capacity: 16, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: ["2021-15.6-1920x1080-ips", { refresh: 144 }],
      battery: ["li-po-pouch", { wh: 60, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-6",
      keyboard: ["kb-1.5", { cols: 19, light: "white" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_GAMING,
  }),
  rival(2025, "lenovo", "Legion 5 Gen 10", {
    body: "workhorse",
    layout: "a",
    size: [345, 260, 19],
    price: 1599,
    parts: {
      processor: "ryzen7-260",
      graphics: "rtx-5060-laptop",
      memory: ["ddr5-5600-sodimm", { capacity: 16, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 1024 }],
      display: ["2021-15.6-2560x1440-ips", { refresh: 165 }],
      battery: ["li-po-pouch", { wh: 75, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-7",
      keyboard: ["kb-1.5", { cols: 19, light: "rgb-zones" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_GAMING_AMD,
    materials: { lid: "aluminium" },
  }),
  rival(2025, "lenovo", "Legion Pro 7i Gen 10", {
    body: "workhorse",
    layout: "a",
    size: [364, 276, 22],
    price: 3199,
    parts: {
      processor: "core-ultra9-275hx",
      graphics: ["rtx-5080-laptop", { switchable: "no" }],
      memory: ["ddr5-5600-sodimm", { capacity: 32, slots: 2 }],
      storage: ["m2-2280-g5", { capacity: 2048 }],
      display: ["2021-16-2560x1600-ips", { refresh: 165 }],
      battery: ["li-po-pouch", { wh: 99.9, thickness: "standard" }],
      cooling: "vapour-chamber",
      wireless: "wifi-7",
      keyboard: ["kb-1.5", { cols: 19, pitch: 18, light: "rgb-per-key" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p",
      speakers: "spk-quad",
    },
    ports: PORTS_GAMING,
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  // ------------------------------------------------ hp
  rival(2025, "hp", "OmniBook 3 15", {
    body: "workhorse",
    layout: "a",
    size: [360, 236, 18],
    price: 699,
    parts: {
      processor: "core5-120u",
      memory: ["ddr5-5600-sodimm", { capacity: 8, slots: 1 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-15.6-1920x1080-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6",
      keyboard: ["kb-1.5", { cols: 19 }],
      trackpad: "pad-110x70",
      webcam: "cam-720p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_BUDGET,
  }),
  rival(2025, "hp", "Laptop 17-cn4000", {
    body: "workhorse",
    layout: "a",
    size: [400, 259, 19],
    price: 749,
    parts: {
      processor: "core5-120u",
      memory: ["ddr5-4800-sodimm", { capacity: 8, slots: 1 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-17.3-1920x1080-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6",
      keyboard: ["kb-1.5", { cols: 19 }],
      trackpad: "pad-110x70",
      webcam: "cam-720p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_BUDGET,
  }),
  rival(2025, "hp", "Laptop 17-cp3000", {
    body: "workhorse",
    layout: "a",
    size: [400, 259, 19],
    price: 849,
    parts: {
      processor: "ryzen7-7730u",
      memory: ["ddr4-3200-sodimm", { capacity: 16, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-17.3-1920x1080-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6",
      keyboard: ["kb-1.5", { cols: 19, light: "white" }],
      trackpad: "pad-110x70",
      webcam: "cam-1080p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_BUDGET,
  }),
  rival(2025, "hp", "OmniBook X 14", {
    body: "blade",
    layout: "a",
    size: [313, 220, 12],
    price: 1199,
    parts: {
      processor: "snapdragon-x1e-78-100",
      memory: ["lpddr5x-soldered", { capacity: 16 }],
      storage: ["m2-2242-g4", { capacity: 512 }],
      display: "2021-14-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 60, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-7",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p-ir",
      speakers: "spk-quad",
    },
    ports: [
      ["usb4-40g", "left"],
      ["usb4-40g", "left"],
      ["usb-a-5g", "right"],
      ["audio-combo", "right"],
    ],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2025, "hp", "EliteBook Ultra G1i 14", {
    body: "blade",
    layout: "a",
    size: [312, 218, 11],
    price: 1999,
    parts: {
      processor: "core-ultra7-268v",
      memory: "lpddr5x-on-package",
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: ["2021-14-2880x1800-oled", { refresh: 60 }],
      battery: ["li-po-pouch", { wh: 60, thickness: "slim" }],
      cooling: "one-fan",
      wireless: "wifi-7",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-125x80", { mechanism: "haptic" }],
      webcam: "cam-5mp-ir",
      speakers: "spk-quad",
    },
    ports: [...PORTS_THIN, ["thunderbolt-4", "right"]],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2025, "hp", "OMEN 16-am0000", {
    body: "workhorse",
    layout: "a",
    size: [360, 263, 22],
    price: 1799,
    parts: {
      processor: "core-ultra7-255h",
      graphics: "rtx-5070-laptop",
      memory: ["ddr5-5600-sodimm", { capacity: 16, slots: 2 }],
      storage: "m2-2280-g4",
      display: ["2021-16-2560x1600-ips", { refresh: 165 }],
      battery: ["li-po-pouch", { wh: 75, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "rgb-zones" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_GAMING,
  }),
  // ------------------------------------------------ dell
  rival(2025, "dell", "XPS 13 9350", {
    body: "blade",
    layout: "a",
    size: [295, 199, 11.5],
    price: 1399,
    parts: {
      processor: "core-ultra7-256v",
      memory: "lpddr5x-on-package",
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-13.3-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "slim" }],
      cooling: "two-fans",
      wireless: "wifi-7",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-110x70", { mechanism: "haptic" }],
      webcam: "cam-1080p-ir",
      speakers: "spk-quad",
    },
    ports: [
      ["thunderbolt-4", "left"],
      ["thunderbolt-4", "right"],
    ],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2025, "dell", "XPS 14 9440", {
    body: "blade",
    layout: "a",
    size: [310, 210, 14],
    price: 1999,
    parts: {
      processor: "core-ultra7-155h",
      graphics: ["rtx-4050-laptop", { switchable: "yes" }],
      memory: ["lpddr5x-soldered", { capacity: 16 }],
      storage: ["m2-2280-g4", { capacity: 1024 }],
      display: ["2021-14-2880x1800-oled", { refresh: 90 }],
      battery: ["li-po-pouch", { wh: 60, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-7",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-125x80", { mechanism: "haptic" }],
      webcam: "cam-1080p-ir",
      speakers: "spk-quad",
    },
    ports: [
      ["thunderbolt-4", "left"],
      ["thunderbolt-4", "left"],
      ["thunderbolt-4", "right"],
      ["microsd-reader", "right"],
      ["audio-combo", "right"],
    ],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
    spend: { material: 1, packing: 1, graphics: 1, cooling: 1 },
  }),
  rival(2025, "dell", "Dell 16 Plus", {
    body: "workhorse",
    layout: "a",
    size: [356, 250, 17],
    price: 1099,
    parts: {
      processor: "core-ultra5-225h",
      memory: ["lpddr5x-soldered", { capacity: 16 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-16-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 60, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-7",
      keyboard: ["kb-1.5", { cols: 19, light: "white" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS,
    materials: { lid: "aluminium" },
  }),
  rival(2025, "dell", "Latitude 7450", {
    body: "workhorse",
    layout: "a",
    size: [312, 223, 15],
    price: 1799,
    parts: {
      processor: "core-ultra7-165u",
      memory: ["lpddr5x-soldered", { capacity: 16 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-14-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 60, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-7",
      keyboard: ["kb-1.5", { light: "white" }],
      trackpad: "pad-110x70",
      webcam: "cam-1080p-ir",
      speakers: "spk-quad",
    },
    ports: [...PORTS, ["usb-a-5g", "left"], ["microsd-reader", "right"]],
    materials: { floor: "aluminium", lid: "aluminium" },
  }),
  rival(2025, "dell", "Alienware 16 Aurora", {
    body: "workhorse",
    layout: "a",
    size: [363, 270, 23],
    price: 1449,
    parts: {
      processor: "core5-220h",
      graphics: "rtx-5060-laptop",
      memory: ["ddr5-5600-sodimm", { capacity: 16, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: ["2021-16-2560x1600-ips", { refresh: 120 }],
      battery: ["li-po-pouch", { wh: 90, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "white" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_GAMING,
  }),
  rival(2025, "dell", "Alienware 16 Area-51", {
    body: "workhorse",
    layout: "a",
    size: [363, 292, 28],
    price: 3199,
    parts: {
      processor: "core-ultra9-275hx",
      graphics: ["rtx-5080-laptop", { switchable: "no" }],
      memory: ["ddr5-6400-sodimm", { capacity: 32, slots: 2 }],
      storage: ["m2-2280-g4", "m2-2280-g4"],
      display: ["2021-16-2560x1600-ips", { refresh: 165 }],
      battery: ["li-po-pouch", { wh: 99.9, thickness: "standard" }],
      cooling: "vapour-chamber",
      wireless: "wifi-7",
      keyboard: ["kb-mech-1.8", { cols: 19, light: "rgb-per-key" }],
      trackpad: ["pad-125x80", { mechanism: "mechanical" }],
      webcam: "cam-1080p-ir",
      speakers: "spk-quad",
    },
    ports: [...PORTS_GAMING, ["thunderbolt-4", "rear"], ["sd-reader-uhs2", "right"]],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2025, "dell", "Precision 7780", {
    body: "workhorse",
    layout: "a",
    size: [398, 290, 25],
    price: 2599,
    parts: {
      processor: "core-i7-13850hx",
      // Stands in for the RTX A1000 workstation card.
      graphics: ["rtx-3050-laptop", { switchable: "yes" }],
      memory: ["ddr5-5600-sodimm", { capacity: 32, slots: 2 }],
      storage: "m2-2280-g4",
      display: "2021-17.3-1920x1080-ips",
      battery: ["li-po-pouch", { wh: 90, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "white" }],
      trackpad: ["pad-110x70", { mechanism: "mechanical", buttons: "separate" }],
      webcam: "cam-1080p-ir",
      speakers: "spk-stereo-2026",
    },
    ports: [...PORTS, ["thunderbolt-4", "right"], ["ethernet-1g", "rear"], ["sd-reader-uhs2", "right"]],
    materials: { floor: "aluminium", deck: "magnesium", lid: "aluminium" },
  }),
  // ------------------------------------------------ apple
  rival(2025, "apple", "MacBook Air 13 (M4, 2025)", {
    body: "workhorse",
    layout: "a",
    size: [304, 215, 10],
    price: 999,
    parts: {
      processor: "apple-m4",
      memory: ["apple-unified", { capacity: 16 }],
      storage: ["m2-2230-g4", { capacity: 256 }],
      display: "2021-13.3-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "slim" }],
      cooling: "fanless",
      wireless: "wifi-6e",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-125x80", { mechanism: "haptic" }],
      webcam: "cam-1080p",
      speakers: "spk-quad",
    },
    ports: PORTS_MAC_AIR,
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2025, "apple", "MacBook Air 15 (M4, 2025)", {
    body: "workhorse",
    layout: "a",
    size: [340, 238, 10.5],
    price: 1199,
    parts: {
      processor: "apple-m4",
      memory: ["apple-unified", { capacity: 16 }],
      storage: ["m2-2230-g4", { capacity: 256 }],
      display: "2021-15.6-1920x1080-ips",
      battery: ["li-po-pouch", { wh: 60, thickness: "slim" }],
      cooling: "fanless",
      wireless: "wifi-6e",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-145x90", { mechanism: "haptic" }],
      webcam: "cam-1080p",
      speakers: "spk-six",
    },
    ports: PORTS_MAC_AIR,
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2025, "apple", "MacBook Pro 14 (M5, 2025)", {
    body: "workhorse",
    layout: "a",
    size: [313, 221, 15.5],
    price: 1599,
    parts: {
      processor: "apple-m5",
      memory: ["apple-unified", { capacity: 16 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-14-2560x1600-ips",
      battery: ["li-po-pouch", { wh: 75, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6e",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-125x80", { mechanism: "haptic" }],
      webcam: "cam-1080p",
      speakers: "spk-six",
    },
    ports: PORTS_MAC_PRO,
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2025, "apple", "MacBook Pro 16 (M4 Max, 2024)", {
    body: "workhorse",
    layout: "a",
    size: [356, 248, 17],
    price: 3499,
    parts: {
      processor: "apple-m4-max",
      memory: ["apple-unified", { capacity: 36 }],
      storage: ["m2-2280-g4", { capacity: 1024 }],
      display: "2021-16-2560x1600-mini-led",
      battery: ["li-po-pouch", { wh: 99.9, thickness: "standard" }],
      cooling: "vapour-chamber",
      wireless: "wifi-6e",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-160x100", { mechanism: "haptic" }],
      webcam: "cam-1080p",
      speakers: "spk-six",
    },
    ports: PORTS_MAC_PRO,
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  // ------------------------------------------------ asus
  rival(2025, "asus", "Zenbook A14 UX3407RA", {
    body: "blade",
    layout: "a",
    size: [311, 214, 11],
    price: 1099,
    parts: {
      processor: "snapdragon-x1-26-100",
      memory: ["lpddr5x-soldered", { capacity: 16 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-14-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 75, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-7",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p-ir",
      speakers: "spk-stereo-2026",
    },
    ports: [
      ["usb4-40g", "left"],
      ["usb4-40g", "left"],
      ["hdmi-2.1", "left"],
      ["usb-a-5g", "right"],
      ["audio-combo", "right"],
    ],
    materials: { floor: "magnesium", deck: "magnesium", lid: "cfrp" },
  }),
  rival(2025, "asus", "Zenbook S 16 UM5606", {
    body: "blade",
    layout: "a",
    size: [354, 243, 11],
    price: 1599,
    parts: {
      processor: "ryzen-ai9-hx370",
      memory: ["lpddr5x-soldered", { capacity: 32 }],
      storage: ["m2-2280-g4", { capacity: 1024 }],
      display: ["2021-16-2560x1600-ips", { refresh: 120 }],
      battery: ["li-po-pouch", { wh: 75, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-7",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-145x90", { mechanism: "haptic" }],
      webcam: "cam-1080p-ir",
      speakers: "spk-six",
    },
    ports: [...PORTS_AMD, ["sd-reader-uhs2", "right"]],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2025, "asus", "ROG Zephyrus G14 GA403WM", {
    body: "blade",
    layout: "a",
    size: [311, 220, 14],
    price: 1999,
    parts: {
      processor: "ryzen-ai9-hx370",
      graphics: "rtx-5060-laptop",
      memory: ["lpddr5x-soldered", { capacity: 32 }],
      storage: "m2-2280-g4",
      display: ["2021-14-2880x1800-oled", { refresh: 90 }],
      battery: ["li-po-pouch", { wh: 60, thickness: "slim" }],
      cooling: "two-fans",
      wireless: "wifi-7",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p-ir",
      speakers: "spk-quad",
    },
    ports: [
      ["dc-jack", "left"],
      ["hdmi-2.1", "left"],
      ["usb4-40g", "left"],
      ["audio-combo", "left"],
      ["usb-c-10g", "right"],
      ["usb-a-10g", "right"],
      ["microsd-reader", "right"],
    ],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2025, "asus", "ROG Flow Z13 GZ302EA", {
    body: "blade",
    layout: "a",
    size: [300, 204, 13],
    price: 2199,
    parts: {
      processor: "ryzen-ai-max-395",
      memory: ["lpddr5x-soldered", { capacity: 32 }],
      storage: "m2-2230-g4",
      display: "2021-13.3-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 75, thickness: "slim" }],
      cooling: "vapour-chamber",
      wireless: "wifi-7",
      keyboard: ["kb-1.0", { light: "rgb-zones" }],
      trackpad: "pad-110x70",
      webcam: "cam-1080p-ir",
      speakers: "spk-stereo-2026",
    },
    ports: [
      ["usb4-40g", "left"],
      ["usb4-40g", "left"],
      ["usb-a-10g", "right"],
      ["microsd-reader", "right"],
      ["audio-combo", "right"],
    ],
    materials: { floor: "magnesium", deck: "magnesium", lid: "magnesium" },
  }),
  rival(2025, "asus", "ROG Strix G16 G615LR", {
    body: "blade",
    layout: "a",
    size: [354, 264, 23],
    price: 2499,
    parts: {
      processor: "core-ultra9-275hx",
      graphics: "rtx-5070ti-laptop",
      memory: ["ddr5-5600-sodimm", { capacity: 32, slots: 2 }],
      storage: "m2-2280-g4",
      display: ["2021-16-2560x1600-ips", { refresh: 165 }],
      battery: ["li-po-pouch", { wh: 90, thickness: "standard" }],
      cooling: "vapour-chamber",
      wireless: "wifi-7",
      keyboard: ["kb-1.5", { cols: 19, light: "rgb-per-key" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_GAMING,
  }),
  rival(2025, "asus", "ROG Strix G17 G713PI", {
    body: "blade",
    layout: "a",
    size: [395, 283, 24],
    price: 1799,
    parts: {
      processor: "ryzen9-7945hx",
      graphics: "rtx-4070-laptop",
      memory: ["ddr5-4800-sodimm", { capacity: 16, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 1024 }],
      display: ["2021-17.3-2560x1440-ips", { refresh: 240 }],
      battery: ["li-po-pouch", { wh: 90, thickness: "standard" }],
      cooling: "vapour-chamber",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "rgb-zones" }],
      trackpad: "pad-125x80",
      webcam: "cam-720p",
      speakers: "spk-stereo-2026",
    },
    ports: tb(PORTS_GAMING_AMD, "usb-c-10g"),
  }),
  rival(2025, "asus", "ROG Strix SCAR 17 X3D G733PYV", {
    body: "blade",
    layout: "a",
    size: [395, 283, 24],
    price: 3299,
    parts: {
      processor: "ryzen9-7945hx3d",
      graphics: "rtx-4090-laptop",
      memory: ["ddr5-4800-sodimm", { capacity: 32, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 2048 }],
      display: ["2021-17.3-2560x1440-ips", { refresh: 240 }],
      battery: ["li-po-pouch", { wh: 90, thickness: "standard" }],
      cooling: "vapour-chamber",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "rgb-per-key" }],
      trackpad: "pad-125x80",
      webcam: "cam-720p",
      speakers: "spk-stereo-2026",
    },
    ports: tb(PORTS_GAMING_AMD, "usb-c-10g"),
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2025, "asus", "TUF Gaming A17 FA707NU", {
    body: "workhorse",
    layout: "a",
    size: [399, 280, 24],
    price: 1199,
    parts: {
      processor: "ryzen7-7735hs",
      graphics: "rtx-4050-laptop",
      memory: ["ddr5-4800-sodimm", { capacity: 16, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: ["2021-17.3-1920x1080-ips", { refresh: 144 }],
      battery: ["li-po-pouch", { wh: 90, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-6",
      keyboard: ["kb-1.5", { cols: 19, light: "rgb-zones" }],
      trackpad: "pad-110x70",
      webcam: "cam-720p",
      speakers: "spk-stereo-2026",
    },
    ports: tb(PORTS_GAMING_AMD, "usb-c-10g"),
  }),
  // ------------------------------------------------ acer
  rival(2025, "acer", "Swift 14 AI SF14-51", {
    body: "workhorse",
    layout: "a",
    size: [313, 218, 12.5],
    price: 1199,
    parts: {
      processor: "core-ultra5-226v",
      memory: "lpddr5x-on-package",
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: ["2021-14-2880x1800-oled", { refresh: 90 }],
      battery: ["li-po-pouch", { wh: 60, thickness: "slim" }],
      cooling: "one-fan",
      wireless: "wifi-7",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-125x80", { mechanism: "haptic" }],
      webcam: "cam-1080p-ir",
      speakers: "spk-stereo-2026",
    },
    ports: [...PORTS, ["microsd-reader", "right"]],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2025, "acer", "Aspire Go 15 AG15-32P", {
    body: "workhorse",
    layout: "a",
    size: [363, 238, 18],
    price: 679,
    parts: {
      processor: "n150",
      memory: ["ddr5-4800-sodimm", { capacity: 8, slots: 1 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-15.6-1920x1080-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6",
      keyboard: ["kb-1.5", { cols: 19 }],
      trackpad: "pad-110x70",
      webcam: "cam-720p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_BUDGET,
  }),
  rival(2025, "acer", "Aspire 3 A317-55P", {
    body: "workhorse",
    layout: "a",
    size: [401, 253, 19],
    price: 699,
    parts: {
      processor: "n200",
      memory: ["ddr4-3200-sodimm", { capacity: 8, slots: 1 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-17.3-1920x1080-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6",
      keyboard: ["kb-1.5", { cols: 19 }],
      trackpad: "pad-110x70",
      webcam: "cam-720p",
      speakers: "spk-stereo-2026",
    },
    ports: [...PORTS_BUDGET, ["ethernet-1g", "left"]],
  }),
  rival(2025, "acer", "Aspire 17 A17-51M", {
    body: "workhorse",
    layout: "a",
    size: [401, 264, 20],
    price: 849,
    parts: {
      processor: "core5-120u",
      memory: ["ddr5-4800-sodimm", { capacity: 16, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-17.3-1920x1080-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "white" }],
      trackpad: "pad-110x70",
      webcam: "cam-1080p",
      speakers: "spk-stereo-2026",
    },
    ports: [...PORTS, ["ethernet-1g", "left"], ["usb-a-5g", "right"]],
    materials: { lid: "aluminium" },
  }),
  rival(2025, "acer", "Aspire 17 AI A17-52M", {
    body: "workhorse",
    layout: "a",
    size: [401, 264, 20],
    price: 1149,
    parts: {
      processor: "core-ultra5-225h",
      memory: ["ddr5-5600-sodimm", { capacity: 16, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-17.3-1920x1080-ips",
      battery: ["li-po-pouch", { wh: 60, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "white" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p",
      speakers: "spk-stereo-2026",
    },
    ports: [...PORTS, ["ethernet-1g", "left"], ["usb-a-5g", "right"]],
    materials: { lid: "aluminium" },
  }),
  rival(2025, "acer", "Nitro V 16 ANV16-42", {
    body: "workhorse",
    layout: "a",
    size: [360, 270, 23],
    price: 1349,
    parts: {
      processor: "ryzen5-240",
      graphics: "rtx-5050-laptop",
      memory: ["ddr5-5600-sodimm", { capacity: 16, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: ["2021-16-1920x1200-ips", { refresh: 165 }],
      battery: ["li-po-pouch", { wh: 60, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "white" }],
      trackpad: "pad-110x70",
      webcam: "cam-720p",
      speakers: "spk-stereo-2026",
    },
    ports: tb(PORTS_GAMING_AMD, "usb-c-10g"),
  }),
  rival(2025, "acer", "Nitro 17 AN17-72", {
    body: "workhorse",
    layout: "a",
    size: [400, 290, 26],
    price: 1399,
    parts: {
      processor: "core-i5-14500hx",
      graphics: "rtx-4060-laptop",
      memory: ["ddr5-5600-sodimm", { capacity: 16, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 1024 }],
      display: ["2021-17.3-1920x1080-ips", { refresh: 144 }],
      battery: ["li-po-pouch", { wh: 90, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "rgb-zones" }],
      trackpad: "pad-110x70",
      webcam: "cam-720p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_GAMING,
  }),
];

const b = (n: string) => pick(R, n);

const T: Rival[] = [
  trim(b("ThinkPad X1 Carbon Gen 13"), "ThinkPad X1 Carbon Gen 13 (Ultra 5 226V)", 1449, {
    parts: { processor: "core-ultra5-226v" },
  }),
  trim(b("ThinkPad T14 Gen 6"), "ThinkPad T14 Gen 6 (Ultra 5 225U, 32GB, 1TB)", 1649, {
    parts: { memory: ["ddr5-5600-sodimm", { capacity: 32, slots: 2 }], storage: ["m2-2280-g4", { capacity: 1024 }] },
  }),
  trim(b("Laptop 17-cn4000"), "Laptop 17-cn4000 (Core 7 150U)", 1049, {
    parts: { processor: "core7-150u", memory: ["ddr5-4800-sodimm", { capacity: 16, slots: 2 }] },
  }),
  trim(b("XPS 13 9350"), "XPS 13 9350 (Ultra 7 258V, 32GB)", 1799, {
    parts: { processor: "core-ultra7-258v", storage: ["m2-2280-g4", { capacity: 1024 }] },
  }),
  trim(b("MacBook Pro 16 (M4 Max, 2024)"), "MacBook Pro 16 (M4 Pro, 2024)", 2499, {
    parts: { processor: "apple-m4-pro", memory: ["apple-unified", { capacity: 24 }], storage: ["m2-2280-g4", { capacity: 512 }] },
  }),
  trim(b("Aspire 17 AI A17-52M"), "Aspire 17 AI A17-52M (Ultra 7 255H, 32GB)", 1499, {
    parts: { processor: "core-ultra7-255h", memory: ["ddr5-5600-sodimm", { capacity: 32, slots: 2 }], storage: ["m2-2280-g4", { capacity: 1024 }] },
  }),
];

export const F2025: Rival[] = [...R, ...T];
