import { pick, type Port, type Rival, rival, trim } from "./kit";

// ------------------------------------------------------------------ 2024

const tb = (list: Port[], to: string): Port[] =>
  list.map(([id, side]) => [id === "thunderbolt-4" ? to : id, side]);

const PORTS: Port[] = [
  ["thunderbolt-4", "left"],
  ["thunderbolt-4", "left"],
  ["hdmi-2.1", "left"],
  ["usb-a-5g", "right"],
  ["audio-combo", "right"],
];
const PORTS_AMD = tb(PORTS, "usb4-40g");
const PORTS_THIN: Port[] = [
  ["thunderbolt-4", "left"],
  ["thunderbolt-4", "left"],
  ["audio-combo", "right"],
];
const PORTS_GAMING: Port[] = [
  ["usb-a-5g", "left"],
  ["usb-c-10g", "left"],
  ["audio-combo", "left"],
  ["dc-jack", "rear"],
  ["hdmi-2.1", "rear"],
  ["ethernet-1g", "rear"],
  ["thunderbolt-4", "rear"],
  ["usb-a-5g", "right"],
];
const PORTS_GAMING_AMD = tb(PORTS_GAMING, "usb-c-10g");
const PORTS_BUDGET: Port[] = [
  ["dc-jack", "left"],
  ["hdmi-2.1", "left"],
  ["usb-a-5g", "left"],
  ["usb-c-5g", "left"],
  ["usb-a-5g", "right"],
  ["audio-combo", "right"],
];

const PORTS_MAC_AIR: Port[] = [
  ["dc-jack", "left"],
  ["usb4-40g", "left"],
  ["usb4-40g", "left"],
  ["audio-combo", "right"],
];
const PORTS_MAC_PRO: Port[] = [
  ["dc-jack", "left"],
  ["usb4-40g", "left"],
  ["usb4-40g", "left"],
  ["audio-combo", "left"],
  ["usb4-40g", "right"],
  ["hdmi-2.1", "right"],
  ["sd-reader-uhs2", "right"],
];

const R: Rival[] = [
  // ------------------------------------------------ lenovo
  rival(2024, "lenovo", "ThinkPad X1 Carbon Gen 12", {
    body: "workhorse",
    layout: "a",
    size: [315, 222, 11.5],
    price: 1899,
    parts: {
      processor: "core-ultra7-165u",
      memory: ["lpddr5x-soldered", { capacity: 16 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-14-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 60, thickness: "slim" }],
      cooling: "one-fan",
      wireless: "wifi-7",
      keyboard: ["kb-1.5", { light: "white" }],
      trackpad: ["pad-110x70", { mechanism: "mechanical", buttons: "separate", stick: "yes" }],
      webcam: "cam-5mp-ir",
      speakers: "spk-quad",
    },
    ports: [...PORTS, ["usb-a-5g", "left"]],
    materials: { floor: "magnesium", deck: "magnesium", lid: "cfrp" },
  }),
  rival(2024, "lenovo", "ThinkPad T14 Gen 5", {
    body: "workhorse",
    layout: "a",
    size: [314, 220, 14.5],
    price: 1299,
    parts: {
      processor: "core-ultra5-125u",
      memory: ["ddr5-5600-sodimm", { capacity: 16, slots: 1 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-14-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 60, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { light: "white" }],
      trackpad: ["pad-110x70", { mechanism: "mechanical", buttons: "separate", stick: "yes" }],
      webcam: "cam-1080p-ir",
      speakers: "spk-stereo-2026",
    },
    ports: [...PORTS, ["usb-a-5g", "left"], ["ethernet-1g", "right"]],
    materials: { lid: "aluminium" },
  }),
  rival(2024, "lenovo", "ThinkPad E16 Gen 2 AMD", {
    body: "workhorse",
    layout: "a",
    size: [356, 249, 17],
    price: 999,
    parts: {
      processor: "ryzen5-7535hs",
      memory: ["ddr5-5600-sodimm", { capacity: 16, slots: 2 }],
      storage: ["m2-2242-g4", { capacity: 512 }],
      display: "2021-16-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "white" }],
      trackpad: "pad-110x70",
      webcam: "cam-1080p",
      speakers: "spk-stereo-2026",
    },
    ports: [...PORTS_AMD, ["ethernet-1g", "right"]],
    materials: { lid: "aluminium" },
  }),
  rival(2024, "lenovo", "ThinkPad P16s Gen 3", {
    body: "workhorse",
    layout: "a",
    size: [361, 249, 17],
    price: 1399,
    parts: {
      processor: "core-ultra7-155h",
      memory: ["lpddr5x-soldered", { capacity: 32 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-16-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 60, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "white" }],
      trackpad: ["pad-110x70", { mechanism: "mechanical", buttons: "separate", stick: "yes" }],
      webcam: "cam-1080p-ir",
      speakers: "spk-stereo-2026",
    },
    ports: [...PORTS, ["ethernet-1g", "right"]],
    materials: { floor: "magnesium", lid: "aluminium" },
  }),
  rival(2024, "lenovo", "Yoga Slim 7x", {
    body: "blade",
    layout: "a",
    size: [313, 219, 11],
    price: 1199,
    parts: {
      processor: "snapdragon-x1e-78-100",
      memory: ["lpddr5x-soldered", { capacity: 16 }],
      storage: ["m2-2242-g4", { capacity: 512 }],
      display: ["2021-14-2880x1800-oled", { refresh: 90 }],
      battery: ["li-po-pouch", { wh: 75, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-7",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p-ir",
      speakers: "spk-quad",
    },
    ports: [
      ["usb4-40g", "left"],
      ["usb4-40g", "left"],
      ["usb4-40g", "right"],
    ],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2024, "lenovo", "LOQ 15IRX9", {
    body: "workhorse",
    layout: "a",
    size: [360, 265, 22],
    price: 1299,
    parts: {
      processor: "core-i5-13450hx",
      graphics: "rtx-4050-laptop",
      memory: ["ddr5-5600-sodimm", { capacity: 16, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: ["2021-15.6-1920x1080-ips", { refresh: 144 }],
      battery: ["li-po-pouch", { wh: 60, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "rgb-zones" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_GAMING,
  }),
  rival(2024, "lenovo", "Legion Pro 7i Gen 9", {
    body: "shelf",
    layout: "a",
    size: [364, 276, 22],
    price: 3199,
    parts: {
      processor: "core-i9-14900hx",
      graphics: ["rtx-4080-laptop", { switchable: "no" }],
      memory: ["ddr5-5600-sodimm", { capacity: 32, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 2048 }],
      display: ["2021-16-2560x1600-ips", { refresh: 165 }],
      battery: ["li-po-pouch", { wh: 99.9, thickness: "standard" }],
      cooling: "vapour-chamber",
      wireless: "wifi-7",
      keyboard: ["kb-1.5", { cols: 19, pitch: 18, light: "rgb-per-key" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_GAMING,
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  // ------------------------------------------------ hp
  rival(2024, "hp", "Laptop 15-fd1000", {
    body: "workhorse",
    layout: "a",
    size: [360, 236, 18],
    price: 699,
    parts: {
      processor: "core5-120u",
      memory: ["ddr5-4800-sodimm", { capacity: 8, slots: 1 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-15.6-1920x1080-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19 }],
      trackpad: "pad-110x70",
      webcam: "cam-720p",
      speakers: "spk-stereo-2026",
    },
    ports: tb(PORTS_BUDGET, "usb-c-5g"),
  }),
  rival(2024, "hp", "Laptop 17-cn4000", {
    body: "workhorse",
    layout: "a",
    size: [400, 259, 19],
    price: 729,
    parts: {
      processor: "core5-120u",
      memory: ["ddr5-4800-sodimm", { capacity: 8, slots: 1 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-17.3-1920x1080-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19 }],
      trackpad: "pad-110x70",
      webcam: "cam-720p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_BUDGET,
  }),
  rival(2024, "hp", "Laptop 17-cp3000", {
    body: "workhorse",
    layout: "a",
    size: [400, 259, 19],
    price: 899,
    parts: {
      processor: "ryzen7-7730u",
      memory: ["ddr4-3200-sodimm", { capacity: 16, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-17.3-1920x1080-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "white" }],
      trackpad: "pad-110x70",
      webcam: "cam-1080p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_BUDGET,
  }),
  rival(2024, "hp", "Pavilion Plus 14-ey1000", {
    body: "workhorse",
    layout: "a",
    size: [313, 222, 13],
    price: 1099,
    parts: {
      processor: "ryzen7-8840u",
      memory: ["lpddr5x-soldered", { capacity: 16 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: ["2021-14-2880x1800-oled", { refresh: 90 }],
      battery: ["li-po-pouch", { wh: 45, thickness: "slim" }],
      cooling: "one-fan",
      wireless: "wifi-6e",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p-ir",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_AMD,
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2024, "hp", "Spectre x360 14-eu0000", {
    body: "blade",
    layout: "a",
    size: [314, 229, 13],
    price: 1549,
    parts: {
      processor: "core-ultra7-155h",
      memory: ["lpddr5x-soldered", { capacity: 16 }],
      storage: ["m2-2280-g4", { capacity: 1024 }],
      display: ["2021-14-2880x1800-oled", { refresh: 90 }],
      battery: ["li-po-pouch", { wh: 60, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-7",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-125x80", { mechanism: "haptic" }],
      webcam: "cam-5mp-ir",
      speakers: "spk-quad",
    },
    ports: [...PORTS_THIN, ["usb-a-5g", "right"]],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2024, "hp", "EliteBook 1040 G11", {
    body: "blade",
    layout: "a",
    size: [315, 224, 12.5],
    price: 1999,
    parts: {
      processor: "core-ultra7-165u",
      memory: ["lpddr5x-soldered", { capacity: 16 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-14-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 60, thickness: "slim" }],
      cooling: "one-fan",
      wireless: "wifi-7",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: "pad-125x80",
      webcam: "cam-5mp-ir",
      speakers: "spk-quad",
    },
    ports: [...PORTS, ["usb-a-5g", "left"]],
    materials: { floor: "aluminium", deck: "magnesium", lid: "aluminium" },
  }),
  rival(2024, "hp", "ENVY 17-cr1000", {
    body: "workhorse",
    layout: "a",
    size: [397, 259, 19],
    price: 1499,
    parts: {
      processor: "core-i7-13700h",
      memory: ["ddr4-3200-sodimm", { capacity: 32, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 1024 }],
      display: "2021-17.3-1920x1080-ips",
      battery: ["li-po-pouch", { wh: 60, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "white" }],
      trackpad: "pad-125x80",
      webcam: "cam-5mp-ir",
      speakers: "spk-quad",
    },
    ports: PORTS,
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2024, "hp", "OMEN 16-wf1000", {
    body: "workhorse",
    layout: "a",
    size: [369, 259, 22],
    price: 1799,
    parts: {
      processor: "core-i7-14700hx",
      graphics: "rtx-4070-laptop",
      memory: ["ddr5-5600-sodimm", { capacity: 16, slots: 2 }],
      storage: "m2-2280-g4",
      display: ["2021-16-2560x1600-ips", { refresh: 165 }],
      battery: ["li-po-pouch", { wh: 75, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "rgb-zones" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_GAMING,
  }),
  // ------------------------------------------------ dell
  rival(2024, "dell", "XPS 13 9340", {
    body: "blade",
    layout: "a",
    size: [296, 199, 12],
    price: 1299,
    parts: {
      processor: "core-ultra7-155h",
      memory: ["lpddr5x-soldered", { capacity: 16 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-13.3-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "slim" }],
      cooling: "two-fans",
      wireless: "wifi-7",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-110x70", { mechanism: "haptic" }],
      webcam: "cam-1080p-ir",
      speakers: "spk-quad",
    },
    ports: [
      ["thunderbolt-4", "left"],
      ["thunderbolt-4", "right"],
    ],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2024, "dell", "XPS 14 9440", {
    body: "blade",
    layout: "a",
    size: [310, 210, 14],
    price: 2199,
    parts: {
      processor: "core-ultra7-155h",
      graphics: ["rtx-4050-laptop", { switchable: "yes" }],
      memory: ["lpddr5x-soldered", { capacity: 16 }],
      storage: ["m2-2280-g4", { capacity: 1024 }],
      display: ["2021-14-2880x1800-oled", { refresh: 90 }],
      battery: ["li-po-pouch", { wh: 60, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-7",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-125x80", { mechanism: "haptic" }],
      webcam: "cam-1080p-ir",
      speakers: "spk-quad",
    },
    ports: [
      ["thunderbolt-4", "left"],
      ["thunderbolt-4", "left"],
      ["thunderbolt-4", "right"],
      ["microsd-reader", "right"],
      ["audio-combo", "right"],
    ],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
    spend: { material: 1, packing: 1, graphics: 1, cooling: 1 },
  }),
  rival(2024, "dell", "Inspiron 16 Plus 7640", {
    body: "workhorse",
    layout: "a",
    size: [357, 251, 18],
    price: 1299,
    parts: {
      processor: "core-ultra7-155h",
      memory: ["lpddr5x-soldered", { capacity: 16 }],
      storage: ["m2-2280-g4", { capacity: 1024 }],
      display: ["2021-16-2560x1600-ips", { refresh: 120 }],
      battery: ["li-po-pouch", { wh: 90, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "white" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p",
      speakers: "spk-stereo-2026",
    },
    ports: [...PORTS, ["sd-reader-uhs2", "right"]],
    materials: { floor: "aluminium", lid: "aluminium" },
  }),
  rival(2024, "dell", "Alienware m16 R2", {
    body: "shelf",
    layout: "a",
    size: [358, 272, 21],
    price: 2199,
    parts: {
      processor: "core-ultra9-185h",
      graphics: "rtx-4070-laptop",
      memory: ["ddr5-5600-sodimm", { capacity: 32, slots: 2 }],
      storage: "m2-2280-g4",
      display: ["2021-16-2560x1600-ips", { refresh: 165 }],
      battery: ["li-po-pouch", { wh: 90, thickness: "standard" }],
      cooling: "vapour-chamber",
      wireless: "wifi-7",
      keyboard: ["kb-1.5", { cols: 19, light: "rgb-per-key" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p-ir",
      speakers: "spk-stereo-2026",
    },
    ports: [...PORTS_GAMING, ["sd-reader-uhs2", "right"]],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2024, "dell", "Latitude 7450", {
    body: "workhorse",
    layout: "a",
    size: [312, 223, 15],
    price: 1899,
    parts: {
      processor: "core-ultra7-165u",
      memory: ["lpddr5x-soldered", { capacity: 16 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-14-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 60, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-7",
      keyboard: ["kb-1.5", { light: "white" }],
      trackpad: "pad-110x70",
      webcam: "cam-1080p-ir",
      speakers: "spk-quad",
    },
    ports: [...PORTS, ["usb-a-5g", "left"], ["microsd-reader", "right"]],
    materials: { floor: "aluminium", lid: "aluminium" },
  }),
  rival(2024, "dell", "Precision 7780", {
    body: "workhorse",
    layout: "a",
    size: [398, 290, 25],
    price: 2799,
    parts: {
      processor: "core-i7-13850hx",
      // Stands in for the RTX A1000 workstation card.
      graphics: ["rtx-3050-laptop", { switchable: "yes" }],
      memory: ["ddr5-5600-sodimm", { capacity: 32, slots: 2 }],
      storage: "m2-2280-g4",
      display: "2021-17.3-1920x1080-ips",
      battery: ["li-po-pouch", { wh: 90, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "white" }],
      trackpad: ["pad-110x70", { mechanism: "mechanical", buttons: "separate" }],
      webcam: "cam-1080p-ir",
      speakers: "spk-stereo-2026",
    },
    ports: [...PORTS, ["thunderbolt-4", "right"], ["ethernet-1g", "rear"], ["sd-reader-uhs2", "right"]],
    materials: { floor: "aluminium", deck: "magnesium", lid: "aluminium" },
  }),
  // ------------------------------------------------ apple
  rival(2024, "apple", "MacBook Air 13 (M3, 2024)", {
    body: "workhorse",
    layout: "a",
    size: [304, 215, 10],
    price: 1099,
    parts: {
      processor: "apple-m3",
      memory: ["apple-unified", { capacity: 8 }],
      storage: ["m2-2230-g4", { capacity: 256 }],
      display: "2021-13.3-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "slim" }],
      cooling: "fanless",
      wireless: "wifi-6e",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-125x80", { mechanism: "haptic" }],
      webcam: "cam-1080p",
      speakers: "spk-quad",
    },
    ports: PORTS_MAC_AIR,
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2024, "apple", "MacBook Air 13 (M2, 2022)", {
    body: "workhorse",
    layout: "a",
    size: [304, 215, 10],
    price: 999,
    parts: {
      processor: "apple-m2",
      memory: ["apple-unified", { capacity: 8 }],
      storage: ["m2-2230-g4", { capacity: 256 }],
      display: "2021-13.3-1920x1200-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "slim" }],
      cooling: "fanless",
      wireless: "wifi-6e",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-125x80", { mechanism: "haptic" }],
      webcam: "cam-1080p",
      speakers: "spk-quad",
    },
    ports: PORTS_MAC_AIR,
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2024, "apple", "MacBook Air 15 (M3, 2024)", {
    body: "workhorse",
    layout: "a",
    size: [340, 238, 10.5],
    price: 1299,
    parts: {
      processor: "apple-m3",
      memory: ["apple-unified", { capacity: 8 }],
      storage: ["m2-2230-g4", { capacity: 256 }],
      display: "2021-15.6-1920x1080-ips",
      battery: ["li-po-pouch", { wh: 60, thickness: "slim" }],
      cooling: "fanless",
      wireless: "wifi-6e",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-145x90", { mechanism: "haptic" }],
      webcam: "cam-1080p",
      speakers: "spk-six",
    },
    ports: PORTS_MAC_AIR,
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2024, "apple", "MacBook Pro 14 (M4, 2024)", {
    body: "workhorse",
    layout: "a",
    size: [313, 221, 15.5],
    price: 1599,
    parts: {
      processor: "apple-m4",
      memory: ["apple-unified", { capacity: 16 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-14-2560x1600-ips",
      battery: ["li-po-pouch", { wh: 75, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6e",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-125x80", { mechanism: "haptic" }],
      webcam: "cam-1080p",
      speakers: "spk-six",
    },
    ports: PORTS_MAC_PRO,
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2024, "apple", "MacBook Pro 16 (M4 Max, 2024)", {
    body: "workhorse",
    layout: "a",
    size: [356, 248, 17],
    price: 3499,
    parts: {
      processor: "apple-m4-max",
      memory: ["apple-unified", { capacity: 36 }],
      storage: ["m2-2280-g4", { capacity: 1024 }],
      display: "2021-16-2560x1600-mini-led",
      battery: ["li-po-pouch", { wh: 99.9, thickness: "standard" }],
      cooling: "vapour-chamber",
      wireless: "wifi-6e",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-160x100", { mechanism: "haptic" }],
      webcam: "cam-1080p",
      speakers: "spk-six",
    },
    ports: PORTS_MAC_PRO,
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  // ------------------------------------------------ asus
  rival(2024, "asus", "Zenbook 14 OLED UX3405MA", {
    body: "blade",
    layout: "a",
    size: [313, 220, 12],
    price: 1199,
    parts: {
      processor: "core-ultra5-125h",
      memory: ["lpddr5x-soldered", { capacity: 16 }],
      storage: ["m2-2280-g4", { capacity: 1024 }],
      display: ["2021-14-2880x1800-oled", { refresh: 90 }],
      battery: ["li-po-pouch", { wh: 75, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6e",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p-ir",
      speakers: "spk-stereo-2026",
    },
    ports: [
      ["thunderbolt-4", "left"],
      ["thunderbolt-4", "left"],
      ["hdmi-2.1", "left"],
      ["usb-a-5g", "right"],
      ["audio-combo", "right"],
    ],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2024, "asus", "Zenbook S 16 UM5606", {
    body: "blade",
    layout: "a",
    size: [354, 243, 11],
    price: 1699,
    parts: {
      processor: "ryzen-ai9-hx370",
      memory: ["lpddr5x-soldered", { capacity: 32 }],
      storage: ["m2-2280-g4", { capacity: 1024 }],
      display: ["2021-16-2560x1600-ips", { refresh: 120 }],
      battery: ["li-po-pouch", { wh: 75, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-7",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-145x90", { mechanism: "haptic" }],
      webcam: "cam-1080p-ir",
      speakers: "spk-six",
    },
    ports: [...PORTS_AMD, ["sd-reader-uhs2", "right"]],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2024, "asus", "ROG Zephyrus G14 GA403UV", {
    body: "blade",
    layout: "a",
    size: [311, 220, 15],
    price: 1799,
    parts: {
      processor: "ryzen9-8945hs",
      graphics: "rtx-4060-laptop",
      memory: ["lpddr5x-soldered", { capacity: 16 }],
      storage: "m2-2280-g4",
      display: ["2021-14-2880x1800-oled", { refresh: 90 }],
      battery: ["li-po-pouch", { wh: 60, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-6e",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: "pad-125x80",
      webcam: "cam-1080p-ir",
      speakers: "spk-quad",
    },
    ports: [
      ["dc-jack", "left"],
      ["hdmi-2.1", "left"],
      ["usb4-40g", "left"],
      ["audio-combo", "left"],
      ["usb-c-10g", "right"],
      ["usb-a-10g", "right"],
      ["microsd-reader", "right"],
    ],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2024, "asus", "ROG Zephyrus G16 GU605MI", {
    body: "blade",
    layout: "a",
    size: [354, 246, 15],
    price: 2199,
    parts: {
      processor: "core-ultra9-185h",
      graphics: "rtx-4070-laptop",
      memory: ["lpddr5x-soldered", { capacity: 32 }],
      storage: "m2-2280-g4",
      display: ["2021-16-2560x1600-ips", { refresh: 165 }],
      battery: ["li-po-pouch", { wh: 90, thickness: "standard" }],
      cooling: "vapour-chamber",
      wireless: "wifi-7",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: ["pad-145x90", { mechanism: "mechanical" }],
      webcam: "cam-1080p-ir",
      speakers: "spk-six",
    },
    ports: [...PORTS_GAMING, ["sd-reader-uhs2", "right"]],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2024, "asus", "ROG Strix G17 G713PV", {
    body: "blade",
    layout: "a",
    size: [395, 283, 24],
    price: 1599,
    parts: {
      processor: "ryzen9-7845hx",
      graphics: "rtx-4060-laptop",
      memory: ["ddr5-4800-sodimm", { capacity: 16, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 1024 }],
      display: ["2021-17.3-2560x1440-ips", { refresh: 240 }],
      battery: ["li-po-pouch", { wh: 90, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "rgb-zones" }],
      trackpad: "pad-125x80",
      webcam: "cam-720p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_GAMING_AMD,
  }),
  rival(2024, "asus", "ROG Strix SCAR 17 X3D G733PYV", {
    body: "blade",
    layout: "a",
    size: [395, 283, 24],
    price: 3599,
    parts: {
      processor: "ryzen9-7945hx3d",
      graphics: "rtx-4090-laptop",
      memory: ["ddr5-4800-sodimm", { capacity: 32, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 2048 }],
      display: ["2021-17.3-2560x1440-ips", { refresh: 240 }],
      battery: ["li-po-pouch", { wh: 90, thickness: "standard" }],
      cooling: "vapour-chamber",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "rgb-per-key" }],
      trackpad: "pad-125x80",
      webcam: "cam-720p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_GAMING_AMD,
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2024, "asus", "TUF Gaming A17 FA707NV", {
    body: "workhorse",
    layout: "a",
    size: [399, 280, 24],
    price: 1199,
    parts: {
      processor: "ryzen7-7735hs",
      graphics: "rtx-4050-laptop",
      memory: ["ddr5-4800-sodimm", { capacity: 16, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: ["2021-17.3-1920x1080-ips", { refresh: 144 }],
      battery: ["li-po-pouch", { wh: 90, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "rgb-zones" }],
      trackpad: "pad-110x70",
      webcam: "cam-720p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_GAMING_AMD,
  }),
  // ------------------------------------------------ acer
  rival(2024, "acer", "Swift Go 14 SFG14-72", {
    body: "workhorse",
    layout: "a",
    size: [313, 218, 12.5],
    price: 1149,
    parts: {
      processor: "core-ultra5-125h",
      memory: ["lpddr5x-soldered", { capacity: 16 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: ["2021-14-2880x1800-oled", { refresh: 90 }],
      battery: ["li-po-pouch", { wh: 60, thickness: "slim" }],
      cooling: "one-fan",
      wireless: "wifi-6e",
      keyboard: ["kb-1.0", { light: "white" }],
      trackpad: "pad-110x70",
      webcam: "cam-1080p",
      speakers: "spk-stereo-2026",
    },
    ports: [...PORTS, ["microsd-reader", "right"]],
    materials: { floor: "aluminium", deck: "aluminium", lid: "aluminium" },
  }),
  rival(2024, "acer", "Aspire Go 15 AG15-31P", {
    body: "workhorse",
    layout: "a",
    size: [363, 238, 18],
    price: 649,
    parts: {
      processor: "n100",
      memory: ["ddr4-3200-sodimm", { capacity: 8, slots: 1 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-15.6-1920x1080-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19 }],
      trackpad: "pad-110x70",
      webcam: "cam-720p",
      speakers: "spk-stereo-2026",
    },
    ports: tb(PORTS_BUDGET, "usb-c-5g"),
  }),
  rival(2024, "acer", "Aspire 3 A317-55P", {
    body: "workhorse",
    layout: "a",
    size: [401, 253, 19],
    price: 699,
    parts: {
      processor: "n200",
      memory: ["ddr4-3200-sodimm", { capacity: 8, slots: 1 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-17.3-1920x1080-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19 }],
      trackpad: "pad-110x70",
      webcam: "cam-720p",
      speakers: "spk-stereo-2026",
    },
    ports: [...PORTS_BUDGET, ["ethernet-1g", "left"]],
  }),
  rival(2024, "acer", "Aspire 17 A17-51M", {
    body: "workhorse",
    layout: "a",
    size: [401, 264, 20],
    price: 849,
    parts: {
      processor: "core5-120u",
      memory: ["ddr5-4800-sodimm", { capacity: 16, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: "2021-17.3-1920x1080-ips",
      battery: ["li-po-pouch", { wh: 45, thickness: "standard" }],
      cooling: "one-fan",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "white" }],
      trackpad: "pad-110x70",
      webcam: "cam-1080p",
      speakers: "spk-stereo-2026",
    },
    ports: [...PORTS, ["ethernet-1g", "left"], ["usb-a-5g", "right"]],
    materials: { lid: "aluminium" },
  }),
  rival(2024, "acer", "Nitro V 15 ANV15-51", {
    body: "workhorse",
    layout: "a",
    size: [362, 239, 23],
    price: 1099,
    parts: {
      processor: "core-i5-13420h",
      graphics: "rtx-4050-laptop",
      memory: ["ddr5-4800-sodimm", { capacity: 8, slots: 1 }],
      storage: ["m2-2280-g4", { capacity: 512 }],
      display: ["2021-15.6-1920x1080-ips", { refresh: 144 }],
      battery: ["li-po-pouch", { wh: 60, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "white" }],
      trackpad: "pad-110x70",
      webcam: "cam-720p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_GAMING,
  }),
  rival(2024, "acer", "Nitro 17 AN17-72", {
    body: "workhorse",
    layout: "a",
    size: [400, 290, 26],
    price: 1399,
    parts: {
      processor: "core-i5-14500hx",
      graphics: "rtx-4060-laptop",
      memory: ["ddr5-5600-sodimm", { capacity: 16, slots: 2 }],
      storage: ["m2-2280-g4", { capacity: 1024 }],
      display: ["2021-17.3-1920x1080-ips", { refresh: 144 }],
      battery: ["li-po-pouch", { wh: 90, thickness: "standard" }],
      cooling: "two-fans",
      wireless: "wifi-6e",
      keyboard: ["kb-1.5", { cols: 19, light: "rgb-zones" }],
      trackpad: "pad-110x70",
      webcam: "cam-720p",
      speakers: "spk-stereo-2026",
    },
    ports: PORTS_GAMING,
  }),
];

const b = (n: string) => pick(R, n);

const T: Rival[] = [
  trim(b("ThinkPad X1 Carbon Gen 12"), "ThinkPad X1 Carbon Gen 12 (Ultra 5 125U)", 1399, {
    parts: { processor: "core-ultra5-125u" },
  }),
  trim(b("ThinkPad T14 Gen 5"), "ThinkPad T14 Gen 5 (Ultra 7 165U, 32GB)", 1649, {
    parts: { processor: "core-ultra7-165u", memory: ["ddr5-5600-sodimm", { capacity: 32, slots: 2 }] },
  }),
  trim(b("Laptop 17-cn4000"), "Laptop 17-cn4000 (Core 7 150U)", 1049, {
    parts: { processor: "core7-150u", memory: ["ddr5-4800-sodimm", { capacity: 16, slots: 2 }] },
  }),
  trim(b("EliteBook 1040 G11"), "EliteBook 1040 G11 (Ultra 5 125U)", 1399, {
    parts: { processor: "core-ultra5-125u" },
  }),
  trim(b("XPS 13 9340"), "XPS 13 9340 (32GB, 1TB)", 1699, {
    parts: { memory: ["lpddr5x-soldered", { capacity: 32 }], storage: ["m2-2280-g4", { capacity: 1024 }] },
  }),
  trim(b("MacBook Air 15 (M3, 2024)"), "MacBook Air 15 (M3, 2024, 24GB)", 1699, {
    parts: { memory: ["apple-unified", { capacity: 24 }], storage: ["m2-2230-g4", { capacity: 512 }] },
  }),
  trim(b("MacBook Pro 16 (M4 Max, 2024)"), "MacBook Pro 16 (M4 Pro, 2024)", 2499, {
    parts: { processor: "apple-m4-pro", memory: ["apple-unified", { capacity: 24 }], storage: ["m2-2280-g4", { capacity: 512 }] },
  }),
  trim(b("Aspire 17 A17-51M"), "Aspire 17 A17-51GM", 999, {
    parts: { graphics: "rtx-2050-laptop" },
  }),
];

export const F2024: Rival[] = [...R, ...T];
